software-mansion/react-native-svg

ios/RNSVGPath.m
ios/RNSVGText.m

A few iOS files weren't switched over to the new `strokeDasharray`

Switches RNSVGPath.m and RNSVGText.m strokeDash to new strokeDasharray

---

package.json

In our build scripts, `rnpm` does not 100% accurately insert packages properly. The combination of other dependencies confuses `rnpm` which ultimately causes conflicts and build errors. This is the case for our application, but I suspect it also applies to some other people as well.
This PR is just to remove the postinstall script so the developer can install manually, or via running rnpm themselves.

Remove the postinstall script that runs rnpm.

---

package.json

Should close #18 since that the only reference left (except the one in the README that mention the change of the name).

package.json: update repo url to recent rename

---

android/src/main/java/com/horcrux/svg/RNSVGImageShadowNode.java
android/src/main/java/com/horcrux/svg/RNSVGSvgViewShadowNode.java
android/src/main/java/com/horcrux/svg/RNSVGVirtualNode.java

Fixing RNSVGImageShadowNode to no longer dangerously store a reference
to a DataSource result, since it's only valid for the lifetime of the
onNewResultImpl() method. Instead, the images are rendered from the
Fresco image bitmap cache.
Updating RNSVGVirtualNode to call getScreenDisplayMetrics() instead of
getWindowDisplayMetrics(), since the latter is deprecated.
Synchronizing access to RNSVGSvgViewShadowNode.drawChildren(), since
it can be called by multiple threads simultaneously (the native UI
thread and the asynchronous Image loader callback).

SVG images double rendering on Android

---

android/src/main/java/com/horcrux/svg/RNSVGImageShadowNode.java
android/src/main/java/com/horcrux/svg/RNSVGPathShadowNode.java
android/src/main/java/com/horcrux/svg/RNSVGSvgViewManager.java
android/src/main/java/com/horcrux/svg/RNSVGSvgViewShadowNode.java
android/src/main/java/com/horcrux/svg/RNSVGVirtualNode.java

Since SVG images are loaded asynchronously, we need to invalidate the
view after drawing to the canvas so that the view will be re-rendered.
Storing a reference to the actual SvgView in ViewManager, and passing a
reference to the ViewManager to each shadow node, so that shadow nodes
can invalidate the root SVG view.
(Also fixing a NPE caused by getDefinedBrush() returning null).

Android: SVG Images not rendering the first time a view is displayed

---

ios/RNSVGNode.m

This fixes the crash dsecribed by #95 and causes my graphic to render correctly (the clip-path inside my defs is respected). This is the first iOS code I've ever written (well, copy-pasted :)) so its possible I've done something silly, but hey ... it works!

fixes #95 - crash whenever <Defs> are used on iOS

---

android/src/main/java/com/horcrux/svg/RNSVGViewBoxShadowNode.java

Lucky for me you left a comment in the code pointing to [the draft spec algorithm](https://svgwg.org/svg2-draft/coords.html#ComputingAViewportsTransform). I noticed the following mismatch between the spec and the Android implementation:
Spec:
> The transform applied to content contained by the element is given by translate(translate-x, translate-y) scale(scale-x, scale-y).
Implementation:
```
mMatrix.postScale(scaleX, scaleY);
mMatrix.postTranslate(-translateX * (mFromSymbol ? scaleX : 1), -translateY * (mFromSymbol ? scaleY : 1));
```
Switching the order to match the spec (translate then scale) resolves #98

translate then scale - fixes #98

---

android/src/main/java/com/horcrux/svg/RNSVGViewBoxShadowNode.java

fixes #104 by resetting the matrix at each draw to prevent applying the transforms on top of the previous transforms

Fixes #104 - re-draws on Android apply viewbox transforms repeatedly

---

android/src/main/java/com/horcrux/svg/RNSVGGroupShadowNode.java

This appears to fix #96 on Android ... I'm not much use with iOS although I'm prepared to have a look at it maybe tomorrow. I suspect the same logic problem is tripping up the iOS version too ...

fixes #96 for Android only - viewBox or nested G elements stifle events

---

ios/Elements/RNSVGGroup.m

iOS was suffering a similar logic problem for #96 as Android - slightly worse I think, since G elements would _always_ steal the event on iOS, whereas it needed a double-nested G to steal the event on Android. 
First ObjectiveC code I've ever written :)

fixes #96 for iOS only - viewBox or nested G elements stifle events

---

android/src/main/java/com/horcrux/svg/RNSVGSvgView.java

Sometimes (maybe in modals?) the root is not a ReactRootView, it’s an
object which is not castable to a View.  Check for these cases before
trying to cast.

Handle touches when root is a ViewRootImpl

---

ios/Utils/RCTConvert+RNSVG.m

Font names can be specified as something like `Helvetica-Bold`. This is specially common when using custom fonts. This fix makes sure those supported custom fonts are not accidentally removed.
Fix #122

Better font family check on iOS to support custom fonts

---

elements/ViewBox.js

We can just use the array.prototype native methods for some and reduce here rather than using lodash. Also fixed usage of let to const where the params are not re-assigned.

Remove dependency on lodash in ViewBox.js

---

android/src/main/java/com/horcrux/svg/RNSVGDefsShadowNode.java

When adding clipping paths in a def and changing properties of that clipping path (or its descendants), redraw is triggered only once as updates are never marked as seen.
This change makes sure to call `markUpdateSeen` on all descendants of the Defs node on a `draw`.

Mark all descendants of Defs as seen after a draw

---

ios/Brushes/RNSVGBaseBrush.m
ios/Brushes/RNSVGBrush.m
ios/Brushes/RNSVGPattern.m
ios/Brushes/RNSVGSolidColorBrush.m
ios/Elements/RNSVGImage.m
ios/Elements/RNSVGSvgView.m
ios/Elements/RNSVGUse.m
ios/RNSVG.xcodeproj/project.pbxproj
ios/RNSVGNode.h
ios/Shapes/RNSVGCircle.m
ios/Shapes/RNSVGEllipse.m
ios/Shapes/RNSVGLine.m
ios/Shapes/RNSVGRect.m
ios/Utils/RCTConvert+RNSVG.h
ios/Utils/RCTConvert+RNSVG.m
ios/ViewManagers/RNSVGDefsManager.h
ios/ViewManagers/RNSVGNodeManager.h
ios/ViewManagers/RNSVGSvgViewManager.h
ios/ViewManagers/RNSVGSvgViewManager.m

https://github.com/facebook/react-native/commit/e1577df1fd70049ce7f288f91f6e2b18d512ff4d moves header imports to `<React/*>`. This updates header include path and all imports so build works against react master (soon to be version 0.40.0).
TODO: Update examples when RN 0.40 is out.

Update iOS RN header paths

---

android/src/main/java/com/horcrux/svg/RNSVGSvgViewManager.java

RN Android 0.39 now uses the C based css-layout and it crashes with an error that says that you cannot attach a CSS node without a measure function. The change is based on RN ART and just adds a dummy measure function to fix the issue (see https://github.com/facebook/react-native/blob/master/ReactAndroid/src/main/java/com/facebook/react/views/art/ARTSurfaceViewManager.java#L48).

Add measure function CSSNode to fix error in RN 0.39

---

ios/Brushes/RNSVGPattern.m

This modification was made in cfaca8b3cb166207357b7b945151762db81d3053, but was missing in a private method signature inside RNSVGPattern.m.

Replace RNSVGBrushConverter type with RNSVGPainter

---

README.md

Especially important when integrating React Native into existing applications that rnpm or react-native link don't work.

Add manual Android instructions.

---

README.md

Casing is important for properties. "viewbox" does nothing while "viewBox" works.

Fixed "viewbox" casing in README example

---

android/src/main/java/com/horcrux/svg/SvgViewManager.java

Fixes https://github.com/react-native-community/react-native-svg/issues/340. I imagine this will be a breaking change for react-native versions < 0.45.0.

Replace yoga's YogaNodeAPI with YogaNode

---

android/src/main/java/com/horcrux/svg/VirtualNode.java
ios/RNSVGNode.m

Fix for issue #251.
Since the refactor, the clip path is created just once and cached until the nodes are recreated.
If you animate any of the clip path elements, the cached clip path is always used and nothing animates.
The solution is to recreate the clip path on every getClipPath call during a draw phase. We can use the cached clip path during a hitTest, I did not change that.

Fix clipPath animations

---

elements/Circle.js
elements/ClipPath.js
elements/Defs.js
elements/Ellipse.js
elements/G.js
elements/Image.js
elements/Line.js
elements/LinearGradient.js
elements/Path.js
elements/RadialGradient.js
elements/Rect.js
elements/Symbol.js
elements/TSpan.js
elements/Text.js
elements/TextPath.js
elements/Use.js
lib/extract/extractViewBox.js
package.json

react-native `>=0.46` moved `react-native/Libraries/Renderer/src/renderers/native/createReactNativeComponentClass` to `react-native/Libraries/Renderer/shims/createReactNativeComponentClass`.
This PR import from the new place, but breaks compatibility with react-native `0.45`.

Support react-native 0.46

---

elements/TSpan.js
elements/Text.js

4 instances that missed the 'prop-types' transition

[Quick fix] Missed 4 instances of React.PropTypes

---

RNSVG.podspec

One line change to allow the RNSVG podspec to be used for Apple TV projects.

Podspec support for Apple TV

---

lib/Matrix2D.js

I believe this is a typo, introduced here: https://github.com/react-native-community/react-native-svg/commit/5bd9b40c1725b60f5a034ce5488c488393356593#diff-53fd7ef0f8293582e3a5625fe345b1f9R86

Correct matrix typo

---

.travis.yml
package.json

RN 0.48 uses alpha 12, 0.49 uses beta 5, and 0.50 uses 16.0.0. "*" covers everything and "react-native" specifies what peerDep version it wants anyway.
"react" is listed under devDeps so that we get the correct version for testing.
CI: RN's own tests don't run on Node 4 anymore, test just 6 and 8.

Add "react" to devDeps, set peerDep version to "*", run tests on Node 6 & 8

---

elements/Circle.js
elements/ClipPath.js
elements/Defs.js
elements/Ellipse.js
elements/G.js
elements/Image.js
elements/Line.js
elements/LinearGradient.js
elements/Path.js
elements/RadialGradient.js
elements/Rect.js
elements/Symbol.js
elements/TSpan.js
elements/Text.js
elements/TextPath.js
elements/Use.js
lib/createReactNativeComponentClass.js

While experimenting with the next release of react-native (0.50) I ran into the following error:
This error is caused by a recent change of an internal API found in this https://github.com/facebook/react-native/commit/e9780bdc0f00364359f39e5a76a3e43eadb93a4b commit.
My environment:
- react-native@0.50.0-rc.0
- react@16.0.0
- react-native-svg@5.4.2
This PR is just a proposal and needs to be updated with a conditional check on the react-native version in use. (only apply changes for react-native >= 0.50). Or even a new branch that has react-native@0.50 as `peerDependency`.
Any other suggestions?

Fix for RN 0.50

---

elements/TextPath.js
lib/createReactNativeComponentClass.js

Fix #498 
Sorry, the last PR #486 was merged with this bug.
A patch fix needs to be deployed cc @magicismight 
Current workaround: `npm install --save brunolemos/react-native-svg#rn-50-fix`

Fix createReactNativeComponentClass for RN < 0.50

---

android/src/main/java/com/horcrux/svg/SvgView.java

This is a fix for (#432).
On Android, when completing a multi touch gesture, `handleTouchEvent` is called multiple times with `ACTION_POINTER_UP` - once for each touch pointer. If the first time `mGestureStartTime` is unset, then subsequent calls crash, because they need the start time.
See (#432) for the stack trace of the crash.

fix broken multi touch for Android (#432)

---

lib/extract/extractBrush.js
package.json

There's a bug with the version of UglifyJS that RN/Metro uses which causes an error about "e.length" inside of "color" that was fixed in 2.x. One change to "color" is that `rgbaArray()` was removed and now the call is `rgb().array()`.

Update "color" dep to 2.x to fix RN minifier bug

---

ios/Text/RNSVGTSpan.m

Fix to release allocated memory in hasGlyph method. Based on #518

Fix memory leak in iOS RNSVGTSpan

---

lib/extract/extractBrush.js
lib/extract/extractGradient.js

The `color` library doesn't include alpha when accessing `color.rgb().array()` when the alpha value is 1. Since we always use the alpha value, make it default to 1 when parsing a color.
This fixes a redbox on Android about expecting a double, but receiving null.

Handle color parsing when alpha = 1

---

lib/extract/extractTransform.js

This PR uses optional `cx` and `cy` props from `rotate` to change the origin of a transformation when given. Should fix https://github.com/react-native-community/react-native-svg/issues/242

support rotations around defined points

---

RNSVG.podspec

The tags for this repo *usually* dont have a `v` prefix, so doing a `pod install` with a direct dependency on the podspec fails.
e.g
`pod 'RNSVG', :podspec => 'node_modules/react-native-svg/RNSVG.podspec'` will fail due to the podspec assuming that the git tag has a `v` prefix
The alternative (and better solution) is to update the old git tags to add `v` prefixes, as this will retroactively fix this bug for all versions since 4.1.0.
But I cant fix tags with pull requests, so I could do with some help here.

Fix tag mismatch in podspec

---

ios/RNSVGRenderable.m

**Motivation**
RNSVGNode without 'pointerEvents' consumes touch events of underlying nodes, because the hitArea is added, even if the responsible flag of the node is set to false.
**Fix**
Check for the responsible flag of the node itself instead of the underlying svgView whose responsible flag is true, if any containing node has 'pointerEvents'.

Respect responsible flag of RNSVGNode.

---

android/src/main/java/com/horcrux/svg/ImageShadowNode.java
android/src/main/java/com/horcrux/svg/RenderableShadowNode.java

Issue caused by 2 things:
- Image resources were not properly getting the path due to missing scheme (if required via require('./images/img.png'))
- markUpdated() was not causing a re-render thus image was not updating if it was a resource id after fetching. This is been changed to directly call bitmapTryRender, however, this may not be the best approach to this issue.
Minor note: After making this change, RenderableShadowNode would get a null for images. I put a null check for the alpha parameter to suppress this.

Fixes Android Release images not rendering (Issue #129)

---

ios/Utils/RNSVGPercentageConverter.m

`RNSVGPercentageConverter::isPercentage:` method can hard crash if somebody uses a type which doesn't respond to `length`, e.g. something like this: `[__NSArrayM length]: unrecognized selector sent to instance 0x61800924baf0`. Instead, just return `NO`, this is not a percentage.

Fix crash when passing wrong type to percentage prop on iOS

---

android/src/main/java/com/horcrux/svg/TSpanShadowNode.java
ios/Elements/RNSVGGroup.m
ios/Text/GlyphContext.h
ios/Text/GlyphContext.m
ios/Text/RNSVGTSpan.m
ios/Text/RNSVGText.h
ios/Text/RNSVGText.m
ios/ViewManagers/RNSVGGroupManager.m
ios/ViewManagers/RNSVGRenderableManager.m
lib/extract/extractProps.js
lib/extract/extractTransform.js
package.json

Add comments to glyphcontext and align with android.
Implement correct isWordSeparator predicate.
Cleanup GlyphContext j2objc remnants.

Implement getAlignmentBaseline and getBaselineShift in ios.

---

android/src/main/java/com/horcrux/svg/GlyphPathBag.java

The half of a char in java has a range of [0, 255], so the array's length should be 256.

fix an "out of range" error

---

index.d.ts

Adds exports for all the type definitions (except `NumberProp`)
Also:
- Extracts and exports the string literal union types
- Adds or renames prop types such that every `Foo`
component export also has a `FooProps`
- Adds non-default export of `Svg`, so `import * as Svg ...`
is usable.
- Makes `RadialGradientProps.gradientUnits` optional, like
for `LinearGradientProps.gradientUnits`.
- Adds stronger type for `TransformProps.transform` based
on code in `extractTranform.js` (please double-check!)
- Fixes typo in `DefinationProps` name.
- A handful of minor formatting normalizations.
I also found and put a type fix for the following issues:
- `Symbols` -> `Symbol` (!)
- `Use` errors unless `width` and `height` are provided, and strings? This seems like a bug.
- `Svg` errors if `width` and …

Add exports for prop types, additional type fixes.

---

ios/RNSVGNode.h
ios/RNSVGNode.m
ios/Text/RNSVGGlyphContext.m
ios/Text/RNSVGTSpan.m
ios/Text/RNSVGTextPath.m
ios/Utils/RNSVGBezierElement.m

This is a followup to https://github.com/react-native-community/react-native-svg/pull/604. In the process of cutting the latest Expo SDK, we found a handful more things that needed to be namespaced for RN-SVG to avoid interacting with other versions of itself.

Namespaces or scopes a handful more global iOS symbols

---

ios/Elements/RNSVGSvgView.m

This is a bit of an obscure bug that occurs when using `display: 'none'` to hide layers on iOS.
I've created an Expo Snack that neatly reproduces the problem here: https://snack.expo.io/S1HhgMdKG
The repro steps are included in the snack, but essentially, the problem occurs when you do the following:
1. Hide a layer via `style={{display: 'none'}}`.
2. Mount an `Svg` as a child of the hidden layer.
3. Show the hidden layer by removing the above style.
**Expected behavior:** the Svg renders.
**Actual behavior:** nothing renders.
When the mounting occurs, the `RNSVGSvgView` properly invokes `setNeedsDisplay`; however, because it's situated in a hidden view tree, its `drawRect:` is not invoked. You would expect it to be invoked when the parent view is unhidden, but it's not.
Adding an …

Fix issue where Svg never draws if mounted while parent is hidden

---

android/src/main/java/com/horcrux/svg/UseShadowNode.java
ios/Elements/RNSVGGroup.m
ios/Elements/RNSVGUse.m
ios/RNSVGRenderable.m

iOS didn't have support of touches in `G` and `Use`
Android didn't have support of touches in `Use`
you can use playground project for experiments: https://github.com/maxkomarychev/svgplayground

Add touch support for `Use` and `G`

---

android/src/main/java/com/horcrux/svg/SvgViewShadowNode.java

Sometime I need to pre-render some content. To do that, I simply render it and put a "display: none" attribute on my view. 
Doing that, I get the error : 
I think this fix is just a workaround, it seems to work but I don't think this check should be done here. But I'm not able to do more on Android.
On iOS it works fine. 
version 6.3.1

drawOutput() only when Layout is != 0

---

lib/extract/extractGradient.js

This prevents valid composition patterns such as:
```typescript
class MyStop extends React.Component {
render() {
return <Stop offset="0" stopColor={"#00000000"} stopOpacity="1"/>;
}
}
<LinearGradient>
<MyStop />
...
</LinearGradient>
```
As far as I can tell, the if block directly below this check should prevent the majority of dev errors that this was trying to avoid.

Remove 'child.type === Stop' check from extractGradient

---

android/src/main/java/com/horcrux/svg/PropHelper.java

Fixes the [android arc-drawing issue #325](https://github.com/react-native-community/react-native-svg/issues/325).
Problems were:
1. the `n` calculation has to be rounded before running Math.ceil on it
1. the `(4 / 3)` in the calculation for `k` used integer division since both values are integers. It needs to use float division instead.
1. the step down from double to float during the calculation for `k` should happen at the end of the entire calculation.
This has been tested with both the Svg paths in the issue namely: 
inverse oval mask:
```
<Svg viewbox={`0 0 270 480`} width={270} height={480}>
<Path
d={`
M 0 0 H270 V480 H0z
M 135 240 m -105, 0
a 2,3.8 0 1,0 210,0
a 2,3.8 0 1,0 -210,0z`}
/>
</Svg>
```
and original partial circle
```
<Svg width={270} height={480}>
<Path d={` …
```

Fixes android arc

---

elements/Polygon.js
elements/Polyline.js

When updating `points` prop, `setNativeProps()` must send a valid `d` prop to `this.root` which is a `<Path>' component.
It needs more work, couldn't get it working perfectly. I'm new to RN.

Updated <Polyline> & <Polygon> setNativeProps()

---

android/build.gradle

Making it compatible with react-native 0.56.0
Still can use
ext {
buildToolsVersion = "23.0.1"
minSdkVersion = 16
compileSdkVersion = 23
targetSdkVersion = 23
supportLibVersion = "23.0.1"
}
if you are using older tools.

Upgrade SDK Build Tools for react-native 0.56.0

---

android/src/main/java/com/horcrux/svg/SvgView.java
android/src/main/java/com/horcrux/svg/SvgViewManager.java

It looks like onDropViewInstance does not get called when the entire react
instance is shut down from the native side. To gaurantee that we do not
leak memory, we need to remove the reference to the view in onDetachedFromWindow().

Fix memory leak: remove references to SvgViews in onDetachedFromWindow

---

android/build.gradle

Hi, as React native 0.56.0 is released with MAJOR android changes such as:
-Gradle 3.5.1
-Compile using Android SDK 26
-Google Maven repo
-etc
more about Change log, specially of Android Here, https://github.com/react-native-community/react-native-releases/blob/master/CHANGELOG.md#android-projects-are-now-compiled-using-the-android-26-sdk
and https://github.com/react-native-community/react-native-releases/blob/master/CHANGELOG.md#android-specific-changes
Aslo as Per Google new "**Google Play's target API level requirement**", mentioned here  https://developer.android.com/distribute/best-practices/develop/target-sdk
> Google Play will require that new apps target at least Android 8.0 (API level 26) from August 1, 2018, and that app updates target Android 8.0 from November 1, 2018.
It's …

Update obsolete compile to implemenation

---

lib/extract/extractStroke.js

This PR fixes this error (parseFloat or ParseInt, both work for this fix):

On Android, the strokeMinterLimit cannot be cast into Float

---

ios/RNSVGNode.m

This PR implements the recently released fix for animating clipPaths in ios.
Here's the recent android-only change for reference. 
https://github.com/react-native-community/react-native-svg/commit/c16a9ed4c0f56c55e33788b4f75ef6c5532826d8

fixes animating clipPath in ios

---

elements/Image.js

follow-through this https://github.com/react-native-community/react-native-svg/pull/652
Since i don't have access to old repo, i re-fork this repo.
In RN 0.54 if we create prod build or set JS-DEV = false in dev settings the app will throw error because can't find `Image.propTypes.source`.

chore(Image): Update image prop type to ImageSourcePropType

---

index.d.ts

ReactNative.ViewProperties now has its own "opacity".

removed duplicate property "opacity" from SvgProps

---

ios/ViewManagers/RNSVGNodeManager.m

Returning a nil `shadowView` prevents natively-driven animations from working with SVG nodes, despite the fact that most SVG nodes (and node properties) support native animations.
I'm not entirely sure why `shadowNode` is set to `nil`, but removing the `nil` has been working for us in our app for 6+ months. (Perhaps it's set to `nil` to save on some memory/Yoga-layout overhead?)
I'm fairly confident that this change won't lead to regressions, but I'd be happy to hear from anybody with knowledge of the original code.

Use the React default `shadowView` to allow native animations

---

index.d.ts

Change `<Pattern>` component props' type definitions to correspond with the current implementation of patterns.

Fix TypeScript type definitions for Pattern component props

---

README.md
android/build.gradle

Configuration 'compile' is obsolete and has been replaced with 'implementation' and 'api'.
It will be removed at the end of 2018. For more information see: http://d.android.com/r/tools/update-dependency-configurations.html

Update README.md, changing dependency configuration for Android platform

---

lib/extract/extractViewBox.js

Looks like the logic flipped recently on the viewBox prop validation when cleaning up some of the code.
This change seems to reflect the intention.
Fixes #809

Fix logic for validating viewBox prop

---

elements/TSpan.js
elements/Text.js
elements/TextPath.js
lib/extract/extractText.js

Warning
```
Require cycle: node_modules/react-native-svg/lib/extract/extractText.js -> node_modules/react-native-svg/elements/TSpan.js -> node_modules/react-native-svg/lib/extract/extractText.js
Require cycles are allowed, but can result in uninitialized values. Consider refactoring to remove the need for a cycle.
```
It's not a pretty solution, but short :)

Fix require cycle between extractText.js and TSpan.js

---

android/src/main/java/com/horcrux/svg/SvgView.java

when specify background color in react-native even parent view height/width could become zero
https://github.com/react-native-community/react-native-svg/issues/823

Do not create bitmap with 0 height/width during early render.

---

android/src/main/java/com/horcrux/svg/SvgView.java

This change fixes a bug on Android where the SVG would not be redrawn when the `SvgView` size changes but the React props did not. 
For instance, when a `<Svg style={{ width: '100%', height: '100%' }} />` is contained within a View that can dynamically change sizes.

Invalidate bitmap when view size is changed

---

android/src/main/java/com/horcrux/svg/RenderableViewManager.java

Dynamically added children does not shown on Svg view.
```javascript
import React from 'react'
import { Button } from 'react-native';
import Svg, { Line } from 'react-native-svg'
class Puzzle extends React.Component<{}, {data: number[], current: number}> {
state = { data: [], current: 1 }
onAdd = () => this.setState(state => ({
data: [...state.data, state.current],
current: state.current + 1,
}));
render() {
return (
<View style={{ flex: 1 }}>
<Svg width={100} height={100}>
{
this.state.data.map(p => (
<Line
key={p}
x1={0}
y1={0}
x2={50}
y2={p * 10}
storkeWidth={8}
stroke="#000"
/>
)
}
</Svg>
<Button title="add" onPress={this.onAdd} />
</View>
)
}
}
```
It renders no line even I clicked button.
DOM tree has no problem,
But no lines are visible.
Should show 4 lines.
It only happens when I …

[android] Invalidate SvgView when view hierarchy changes

---

index.d.ts

The spec for opacity says the attribute applies to container elements (except `mask`) and graphic elements.
> ‘opacity’
> 
> * Value:  `<opacity-value>` | inherit
> * Initial:  1
> * **Applies to:  [container elements](https://www.w3.org/TR/SVG11/intro.html#TermContainerElement) (except [‘mask’](https://www.w3.org/TR/SVG11/masking.html#MaskElement)) and [graphics elements](https://www.w3.org/TR/SVG11/intro.html#TermGraphicsElement)**
> * Inherited:  no
> * Percentages:  N/A
> * Media:  visual
> * Animatable:  yes 
– https://www.w3.org/TR/SVG11/masking.html#OpacityProperty
Container elements (except `mask`) include `a`, `defs`, `glyph`, `g`, `marker`, `missin-glyph`, `pattern`, `svg`, `switch` and `symbol`. Out of these `g` and `symbol` have interfaces defined and both have `opacity` added …

Add missing opacity property to container and graphic element types

---

android/build.gradle

This closes #868
adding google() as a build repository in `build.gradle`, as it is required for Android Gradle Plug-in 3.1.2
https://developer.android.com/studio/releases/gradle-plugin

add google for build gradle repository

---

elements/Shape.js

The code in the Shape constructor assumes that `SvgTouchableMixin` contains only functions but [this](https://github.com/facebook/react-native/blob/master/Libraries/Components/Touchable/Touchable.js#L904) was added which breaks this assumption.
This simply makes sure whatever we assign is a function before calling `.bind`.

Fix compat with latest RN master

---

ios/Elements/RNSVGGroup.m

The filtering of `RNSVGGroup` in `hitTest:withEvent:` during the `reactTagAtPoint:` phase is returning the **first** active subviews with `active == TRUE`.
However, as the display order of subviews is reversed, the bottom-most group will be returned if there are more than one active subviews.
Assuming that there are two overlapping groups, if the top group is being clicked after the bottom group has been clicked (active), the bottom group will be returned.
Sample SVG to reproduce the problem:
```jsx
<Svg viewBox="0 0 580 400" preserveAspectRatio="xMidYMid" height="400" width="580">
<G id="svg_g1">
<Rect onPressIn={callback1} id="svg_1" height="400" width="577" y="2" x="1" stroke-width="1.5" stroke="#0fffff" fill="#e2e21f"/>
</G>
<G id="svg_g3">
<Rect onPressIn={callback2} id="svg_3" …
```

[ios] Fix active filtering in hitTest to return the last (top-most) view

---

android/src/main/java/com/horcrux/svg/SvgView.java

During a LayoutAnimation.spring animation it's possible for the SvgView to have negative layout dimensions when used with 100% width/height. In this case, Android crashes with an exception.

Check for negative dimensions before calling Bitmap.createBitmap.

---

index.d.ts

As per discussion on https://github.com/react-native-community/react-native-svg/issues/943, `<Svg>` component accepts the same props as `<G>`, so `SvgProps` should extend `GProps`.
This PR does just that, but on doing so we get the following error from TypeScript compiler:
```
Interface 'SvgProps' cannot simultaneously extend types 'GProps' and 'ViewProps'.
Named property 'pointerEvents' of types 'GProps' and 'ViewProps' are not identical.ts(2320)
```
`GProps` extends `CommonPathProps`, which extends `ResponderProps`. No problem here. The problem seems to be that `pointerEvents` on `ResponderProps` seems to have a wrong type:
```
export interface ResponderProps extends ReactNative.GestureResponderHandlers {
pointerEvents?: (event: any) => any,
}
```
`pointerEvents` is a prop of …

[ts] Fix SvgProps and ResponderProps interfaces.

---

README.md

- Use `metro.config.js` instead of `rn-cli.config.js`.
- React Native 0.59.x ships with `metro.config.js` file, so it will be used as the default config for Metro.
- `metro.config.js` file works on React Native 0.57 and 0.58 too.

Update react-native-svg-transformer documentation

---

index.d.ts

When upgrading to react-native-svg 9.3.1 I got these error messages in Typescript
```
node_modules/react-native-svg/index.d.ts:105:19 - error TS1005: ';' expected.
105 VectorEffectProps {
~
node_modules/react-native-svg/index.d.ts:106:16 - error TS1109: Expression expected.
106   vectorEffect?: "none" | "non-scaling-stroke" | "nonScalingStroke" | "default" | "inherit" | "uri";
~
Found 2 errors.
```
It seems to me that this was caused by forgetting to add the `interface` keyword before `VectorEffectProps`.
This pr fixes that.

Fix typescript error in index.d.ts

---

lib/extract/extractColor.js

this is currently happening on lines 437-441 when converting to the
int32Color
when using hsl values and the saturation set to 0% the conversion from hsl -> rgb is multiplying by 255 to get an rgb value of (255, 255, 255).  This is rgb is used when creating the int32Color which then also multiplies the number by 255 again.  Removing the additional multiplication in the hslToRgb function will give consistent rgb values used to generate the int32Color.

remove extra *255 in hsl conversion

---

index.d.ts

The Image component works with the clipPath (used in one of the examples) and mask props however the TypeScript definition does no reflect this. This change simply updates the ImageProps definition.

Add CommonMaskProps and ClipProps to ImageProps

---

index.d.ts

In the specs can be found that this property may be used, and I have verified the working;
https://github.com/react-native-community/react-native-svg#image
Added missing Image clipPath property to Typescript type definition.
Application using the react-native-svg package
1. Add an Image component with clipPath to your code
2. Run typescript validation
3. Ensure you do NOT see; _Property 'clipPath' does not exist on type..._

Added missing Image clipPath property to type def.

---

android/src/main/java/com/horcrux/svg/PathParser.java
ios/Utils/RNSVGPathParser.m

- ref: https://github.com/react-native-community/react-native-svg/issues/1083

Handle condition where `skip_spaces` could put the index out of range.

---

.gitignore
index.d.ts

Resolves the [issue](https://github.com/react-native-community/react-native-svg/issues/1089)
| iOS     |    ✅    |

Typescript types for SvgUri and other

---

ios/RNSVG.xcodeproj/project.pbxproj

Clear references to fix issues building react-native-svg
This PR fix this issue https://github.com/react-native-community/react-native-svg/issues/1123

Remove references of RNSVGPercentageConverter file

---

src/lib/extract/extractTransform.ts
src/lib/extract/transform.d.ts

It removes the `@ts-ignore` comment and adds types for generated `transform.js` file.

Remove ts-ignore comment

---

android/src/main/java/com/horcrux/svg/PathView.java

I was trying to animate `<Path/>` `d` attribute with `react-native-reanimated`. On iOS it worked well, but on Android, it was rising null pointer exception and the app was crashing. I found that `mPath` is null when it's trying to be used. For some reason, the `reanimated` nodes didn't manage to initialize on time, and initial `setD` was invoked after the initial render of the path. Setting default path value to an empty path solves the issue.
PS: It would be awesome to release this patch before Expo releases SDK 36, so new fixed version of `react-native-svg` will be included 🙏 
`react-native-reanimated` and `react-native-svg` installed in the project
Following code used to fail on Android, works well on iOS
It's a minimal repro, so no visible path will be rendered.
```js
import React …
```

fix: initialize PathView with empty path to support reanimated on Android

---

src/ReactNativeSVG.web.ts

So onPress handlers are not working on web elements like `<Path />`. I've noticed that because I am creating a graph in `react-native-svg` that works on all platforms and I needed the onPress functionality on a Path element. I've searched for some issues and saw that others are suffering the same problem:
- [608](https://github.com/react-native-community/react-native-svg/issues/608#issuecomment-438376252)
- [599](https://github.com/react-native-community/react-native-svg/issues/599#issuecomment-507403339) 
- #1078
I think that this problems are related to [this line](https://github.com/necolas/react-native-web/blob/250ee3c234196fdddf6e5189c572a292566c3cb2/packages/react-native-web/src/exports/createElement/index.js#L58) that validates if the prop name is a valid prop for touchables on the …

Fix onPress handler mapping on web elements

---

src/ReactNativeSVG.web.ts

Fixes https://github.com/react-native-community/react-native-svg/issues/1244
1. Init a project with `create-react-app` and `react-native-web`
2. Add this fork of `react-native-svg` as a dependency and add a random SVG using it without setting `accessible` prop
1. Try to focus SVG elements: it will not be possible unless you enforce `accessible={true}`

Delete regression that make every component accessible by default

---

android/src/main/java/com/horcrux/svg/PathParser.java
android/src/main/java/com/horcrux/svg/RenderableView.java

1. When animating `Path` with `d` attribute and `nativeDriver:true`, React sometimes sets `null` to the property, and it got crashed. (Still happens on `RN 0.61.4` and `react-native-svg 10.1.0`)
https://github.com/react-native-community/react-native-svg/issues/951#issuecomment-487968402
https://github.com/react-native-community/react-native-svg/issues/951#issuecomment-488825825
2. When animating `stroke` on Android, the color seems to be wrong, so I modified it by copying the implementation detail from `fill`
Try animating stroke, and path, using `useNativeDriver:true`
https://gist.github.com/HelloCore/bafdf02644012bb47d85e828dd734e41

fix(android): animated stroked path with useNativeDriver: true

---

.gitignore
RNSVG.podspec

Hello! In order to manually link react-native-svg in an existing iOS project that uses Bazel, I have added two changes:
* Change `build` to `build/` in `.gitignore`. This doesn't add any files (it should still exclude Android gradle files), but it allows us to include our generated Bazel BUILD file when we build our app.
* Add `React/RCTImage` as a dependency to the podspec. This allows the package to build without errors (was originally getting the issue `'React/RCTImageLoader.h' file not found` as described in the README).

[chore] Fix podspec/gitignore to work with Bazel builds (iOS)

---

ios/RNSVGNode.m

* Do not retain copy of CGPath
This PR fixes a memory leak related to clip paths
When rendering SVG's containing clip paths we noticed a memory leak when cycling the app between foreground/background. Looking at the history related allocation it was recently changed from simply a CGRetain of _clipNode to a copying and transform of the same. The CGPathRetain call is still there which seems wrong as a copy will introduce the reference needed.
Run code with SVG that triggers the affected code path and make sure there are no memory leaks. Make sure the Retain call did not have other obscure reasons for being left in.

bugfix: Memory leak in SVG with clip path

---

ios/Elements/RNSVGImage.m

* Fix crash on double release
Make sure image is set to nil once it has been released. This ensures
that we won't release it more than once.
Fixes #1323
This repository contains an example of how to make current version crash.
https://github.com/op/svg-cat-image-boom
Point your package to `file:/.../local/path/to/react-native-svg` and run `yarn upgrade --latest --pattern react-native-svg` and you should be good to go.

Fix crash on double release

---

src/index.d.ts

Some Typescript type declarations are missing and the editor complains.
See [this issue](https://github.com/react-native-community/react-native-svg/issues/1332#issuecomment-608281851) for more details.
The issue came up by creating wrappers to the `SVG` elements while still preserving the underlying `props`. For example a Circle can be wrapped with the following declaration (the link contains the full declaration):
```
class Circle extends React.PureComponent<
{
id: string;
onPress: (e: GestureResponderEvent, id: string) => void;
} & RNSVG.Circle
>
```
The editor squiggles the word 'Circle' in `RNSVG.Circle` (after the extends).
The reason is because `Circle` is a type but was only exported as `const`.
Before:
```
export const Circle: React.ComponentClass<CircleProps>;
```
After:
``` …
```

Added exports of types to resolve editor squiggling

---

ios/RNSVG.xcodeproj/project.pbxproj

Fix ForeignObject not being linked correctly to the IOS project data file. This allows you to use the ForeignObject component on IOS. 
Import and render a ForeignObject component if it doesn't crash then it works.

IOS ForeignObject fix

---

android/build.gradle

according to [this documentation](https://developer.android.com/studio/releases/gradle-plugin#behavior_changes), it's no longer need to specify buildToolsVersion in gradle file. so I removed it.

bumped AGP to 3.6.1 and removed buildToolsVersion

---

android/src/main/java/com/horcrux/svg/ClipPathView.java
android/src/main/java/com/horcrux/svg/VirtualView.java
apple/RNSVGNode.m

Fix #1409
The `clipRule` prop should be used on graphics elements.
Not on ClipPath itself.
Run example in #1409
None
#1409

Fix clipRule in Android #1409

---

RNSVG.podspec

Latest Xcode 12 fails to build while without a module to depend on `React-Core` directly hence this change is necessary for all native modules on iOS. For more details please check: facebook/react-native#29633
Recently, all React Native modules made this necessary change.
React Native SVG is one of the latest that didn't fix this.
Use this branch to install with an app running on Xcode 12.
Xcode 12 & a recent version of React Native (like 0.64)

Xcode 12 compatibility fix

---

RNSVG.podspec

Including macos files will cause compile errors for tvOS app.
Use react-native-svg in [react-native-tvos](https://github.com/react-native-tvos/react-native-tvos) app.

Exclude macos files on tvOS

---

README.md

It is not any different to import react-native-svg in Expo apps than it is otherwise
README is incorrect
https://snack.expo.dev/@brents/uplifting-pretzels
Run this: https://snack.expo.dev/@brents/uplifting-pretzels
Notice that you don't need to do `import * as Svg`
n/a
n/a
- [n/a] I updated the typed files (typescript)
- [n/a] I added a test for the API in the `__tests__` folder

Fix README re: Expo usage

---

src/index.d.ts

The SVG module supports the RN transform API. In fact, it is the recommended approach when animating SVG transform. This exposes the API via the TS types.

fix(🐛): Expose RN Transform API in types

---

.github/workflows/macos-build-test.yml

Added empty CI job for building macOS so it can be run on the proper PR: https://github.com/react-native-svg/react-native-svg/pull/1704

feat: add empty CI job so it runs on PR then

---

apple/RNSVGRenderable.m

This PR fixes low-quality masks on iOS, as reported in #1098.
This was caused by the bitmap for the mask being created with [CGBitmapContextCreate()](https://developer.apple.com/documentation/coregraphics/1455939-cgbitmapcontextcreate) which does not take into account the device's pixel-density, unlike [UIGraphicsBeginImageContextWithOptions()](https://developer.apple.com/documentation/uikit/1623912-uigraphicsbeginimagecontextwitho).
To fix it, the pixel-density is retrieved using `[[UIScreen mainScreen] scale]` and it is used as a scale factor for the mask bitmap.
I've tested using this sample:
```jsx
<Svg width={300} height={180}>
<Defs>
<LinearGradient id="redGrad" x1="0" y1="0" x2="1" y2="0">
<Stop offset="0" stopColor="#FF0000" stopOpacity="0" />
<Stop offset="1" stopColor="#FF0000" …
```

Fix low-quality masks on iOS

---

src/ReactNativeSVG.web.ts
src/lib/SvgTouchableMixin.ts
src/lib/util.ts

Fixes  https://github.com/react-native-svg/react-native-svg/issues/1471
As described in https://github.com/react-native-svg/react-native-svg/issues/1471, each SVG element is focusable/tabable on web by default. This can create issues in keyboard navigation. 
As explained by @jondkoon https://github.com/react-native-svg/react-native-svg/issues/1471#issuecomment-716953627, the TouchableMixin attaches blur handler which makes SVG elements focusable. 
So, to solve this, we only attach touchable mixin handlers if the element has any touchable props.
Before:
Each element is focusable
https://user-images.githubusercontent.com/23293248/117712663-3d163680-b1f2-11eb-8887-df2cf45dae91.mov
After:
No element is focusable
https://user-images.githubusercontent.com/23293248/117712859-7fd80e80-b1f2-11eb-9f …

fix#1471: every element is focusable on web

---

.github/workflows/android-build-test.yml
.github/workflows/ios-build-test.yml
.github/workflows/macos-build-test.yml

PR changing CI jobs target to `main` branch since it was changed from `develop`.

fix: change ci jobs to main

---

src/xml.tsx

Fix for interpreting an HTML error response as svg data, and then crash when this cannot be parsed as well formed XML
closes #1500 
n/a
Just a a clean project with the latest versions of react-native and react-native-svg
Include this in App.js
```
<SvgUri width={100} height={100} uri={'https://dev.w3.org/SVG/tools/svgweb/samples/svg-files/ruby.svg'} />
```
and you'll get:
Then make the file name invalid
```
<SvgUri width={100} height={100} uri={'https://dev.w3.org/SVG/tools/svgweb/samples/svg-files/xruby.svg'} />
```
and you'll get:
With the fix you'll get this instead:

Fix for SvgUri and SvgCssUri crashing on non-existing svg files

---

src/lib/extract/extractPolyPoints.ts

Fix bug in extractPolyPoints where an uppercase exponent (E) in a polygon (e.g. 4.7E-17) wouldn't be considered an exponent, only a lowercase one (4.7e-17)

Fix issue #1418

---

README.md
TestsExample/src/SampleTest.tsx
src/css.tsx
src/index.d.ts
src/index.js.flow

In PR #1266, support was added for setting an `onError` property on `SvgUri`. This PR adds the same to `SvgCssUri`.
This should now work: 
```ts
import React, {Component} from 'react';
import {  SvgCssUri } from 'react-native-svg';
class Example extends Component {
state={
uri: 'https://dev.w3.org/SVG/tools/svgweb/samples/svg-files/xruby.svg',
}
render() {
return (
<SvgCssUri width={100} onError={() => this.setState({uri: 'https://dev.w3.org/SVG/tools/svgweb/samples/svg-files/ruby.svg'})} height={100} uri={this.state.uri} />
);
}
}
```
This PR is on request from @WoLewicki in PR #1503.

Add support for setting an onError prop on SvgCssUri

---

src/elements/Stop.tsx

Hi, not sure why this has props declared here (`Component<StopProps, {}>` handles that) and it results in a TS error (TS 4.7.2):
```
node_modules/react-native-svg/src/elements/Stop.tsx:8:3 - error TS2612: Property 'props' will overwrite the base property in 'Component<StopProps, {}, any>'. If this is intentional, add an initializer. Otherwise, add a 'declare' modifier or remove the redundant declaration.
8   props!: StopProps;
~~~~~
Found 1 error. Watching for file changes.
```
`tsc` passes but other lint/test tasks fail for unrelated reasons

Fix Stop.tsx error TS2612: Property 'props' will overwrite the base property in 'Component<StopProps, {}, any>'

---

package.json
src/ReactNativeSVG.ts
src/elements/Stop.tsx
src/elements/Svg.tsx
src/lib/extract/types.ts
src/xml.tsx

Added missing component props and made `Svg*` component props extend `SvgProps`. Also removed custom `Color` type which is now just `ColorValue` from `react-native`. Should fix #1812, #1811.
Try and use components from `USAGE` section.

fix: types from lib folder

---

src/xml.tsx

When the svg code has some blank in style attribute,like this `style="white-space: pre; "`
it was throw an error `Cannot read property 'trim' of undefined`.
Test Svg Code: 
```
<?xml version="1.0" encoding="UTF-8" standalone="no" ?><!DOCTYPE svg PUBLIC "-//W3C//DTD SVG 1.1//EN" "http://www.w3.org/Graphics/SVG/1.1/DTD/svg11.dtd"><svg xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink" version="1.1" width="1119" height="286.47938144329896" viewBox="0 0 1119 286.47938144329896" xml:space="preserve"><g transform="matrix(1 0 0 1 296.43 94.71)" style=""  ><text xml:space="preserve" font-family="Times New Roman" font-size="48" font-style="normal" font-weight="normal" style="stroke: none; stroke-width: 1; stroke-dasharray: none; stroke-linecap: butt; stroke-dashoffset: …
```

fix style attribute space

---

src/LocalSvg.tsx

PR adding proper typings for `asset` prop of `LocalSvg` based on `Image.resolveAssetSource()` typings. Based on #1593 by @pratyushok. Should fix #1537.

fix: remove tsignore in LocalSvg and provide correct types

---

src/elements/Shape.tsx

The constructor with context is deprecated and occurs types error in `react-native@69+`.
See https://reactjs.org/docs/legacy-context.html
With react-native 0.69+ project try below.
```
const AnimCircle = Animated.createAnimatedComponent(Circle);
```
then the error occurs.

Fix constructor with deprecated context

---

src/elements/Marker.tsx
src/elements/Mask.tsx

Fixes #1210 again
This PR is rewrite version of #1800 refactored with 286c02fac46ab5ac65f67a3ae2b99d3f1d37a18c
After #1800 merged, the refactoring 286c02fac46ab5ac65f67a3ae2b99d3f1d37a18c was performed and enum declaration was back to previous one.
So type error mentioned at #1210 for maskUnits should occurred again.
Wouldn't you better to refactor the enum like this PR?
This PR doesn't affect any executable code.
Only change type declaration
None
None
Only changes the Typescript declaration

feat: fix broken enum declaration

---

src/ReactNativeSVG.ts

Exported all types from `lib/extract/types.tsx` since most of them were available before refactor done in #1806.

fix: export types from lib which were available before

---

src/ReactNativeSVG.web.ts

This PR is fixing part of issue https://github.com/react-native-svg/react-native-svg/issues/1824
Props _translateX_ and _translateY_ are ignored on web. This PR is addressing it the same way as it is already done for _originX_ and _originY_.
This PR is not addressing the issue of _transform_ as stated in issue.
| iOS     |    tested     |
| Android |    not affecting     |
| Web |    ✅     |

Add support for translateX and translateY on web

---

.github/workflows/ios-build-test.yml
.github/workflows/macos-build-test.yml

Added improved `iOS` CI jobs based on https://github.com/software-mansion/react-native-reanimated/pull/3448 which is probably based on changes from https://github.com/callstack/react-native-slider/pull/400 😅

feat: change ios CI

---

FabricExample/ios/Podfile.lock
android/src/main/java/com/horcrux/svg/RenderableViewManager.java

Previous method definition resulted in not overriding the base method so after the props update, `SvgView` was not invalidated and redrawn. Should fix #1840.

fix: make svg invalidate after props update

---

apple/Elements/RNSVGClipPath.mm
apple/Elements/RNSVGDefs.mm
apple/Elements/RNSVGForeignObject.mm
apple/Elements/RNSVGGroup.mm
apple/Elements/RNSVGImage.mm
apple/Elements/RNSVGLinearGradient.mm
apple/Elements/RNSVGMarker.mm
apple/Elements/RNSVGMask.mm
apple/Elements/RNSVGPath.mm
apple/Elements/RNSVGPattern.mm
apple/Elements/RNSVGRadialGradient.mm
apple/Elements/RNSVGSvgView.mm
apple/Elements/RNSVGSymbol.mm
apple/Elements/RNSVGUse.mm
apple/Shapes/RNSVGCircle.mm
apple/Shapes/RNSVGEllipse.mm
apple/Shapes/RNSVGLine.mm
apple/Shapes/RNSVGRect.mm
apple/Text/RNSVGTSpan.mm
apple/Text/RNSVGText.mm
apple/Text/RNSVGTextPath.mm
apple/Utils/RNSVGFabricConversions.h

This PR replaces bad double-quotes imports (which break Swift interop) with good angle-bracket imports.
The forbidden pattern is: `#import "RCT`, except for `#import "RCTConvert+RNSVG.h"` which is okay.
See also:
* https://github.com/software-mansion/react-native-reanimated/pull/3150
* https://github.com/software-mansion/react-native-gesture-handler/pull/2180
* https://github.com/software-mansion/react-native-screens/pull/1572
Check if Example and FabricExample apps compile successfully.

Use angle-bracket imports

---

android/src/main/java/com/horcrux/svg/RenderableView.java
android/src/main/java/com/horcrux/svg/VirtualView.java

On old `react-native` versions (e.g. 0.64.4), property setters on Android were handled differently, which resulted in calling `Dynamic` setters for e.g. `fill`, `matrix` and `stroke` prop. Since `JS` code has been changed, the props on the native side look a bit different. It lead to bugs in mentioned props, which was not spotted since the code was tested only on the newer versions of `react-native`, where new view managers are used and props do not resolve in `Dynamic` setters.

fix: setters for old react native versions

---

android/src/main/java/com/horcrux/svg/RenderableViewManager.java
android/src/main/java/com/horcrux/svg/SvgView.java

Duplication of #1542 on the newest main with a null check on `svgView`.

fix: bitmap nulled before screen transition

---

.github/workflows/android-build-test.yml

This PR should hopefully fix CI jobs for Example and FabricExample apps being cancelled by using `matrix.working_directory` variable in `concurrency.group` identifier.

Fix concurrent CI

---

Example/.gitignore
Example/.prettierrc.js
Example/ios/Podfile.lock
Example/package.json
Example/src/examples/PanResponder.tsx
Example/yarn.lock
FabricExample/.gitignore
FabricExample/ios/Podfile.lock
FabricExample/package.json
FabricExample/yarn.lock
README.md

PR bumping `Example` and `FabricExample` apps to rn 0.70.

chore: bump examples to rn 0.70

---

android/src/main/java/com/horcrux/svg/RenderableViewManager.java
android/src/main/java/com/horcrux/svg/SvgView.java

PR fixing the regression introduced in #1844. In that PR we set `mRemovedFromReactViewHierarchy` after one of `SvgView`'s children has been removed, resulting in not being able to update it after one of the components in its hierarchy has been removed. In this PR the behavior has been changed, now we subscribe to `startViewTransition` which should be called only by `react-native-screens` when the screen starts its removal animation. It should still work for old issues as well as the new ones.
Fix originally proposed by @msvargas in https://github.com/software-mansion/react-native-screens/issues/773#issuecomment-770043776.
https://github.com/software-mansion/react-native-screens/issues/773#issuecomment-769418173
https://github.com/react-native-svg/react-native-svg/issues/1859 …

fix: restore bitmap recycling on children changes

---

RNSVG.podspec

RCT_NEW_ARCH_ENABLED seems to be always true (even when its value is '0') without an explicit check

Fixed RCT_NEW_ARCH_ENABLED in podspec

---

android/src/main/java/com/horcrux/svg/RenderableViewManager.java
apple/Elements/RNSVGClipPath.mm
apple/Elements/RNSVGForeignObject.mm
apple/Elements/RNSVGGroup.mm
apple/Elements/RNSVGImage.mm
apple/Elements/RNSVGLinearGradient.mm
apple/Elements/RNSVGMarker.mm
apple/Elements/RNSVGMask.mm
apple/Elements/RNSVGPath.mm
apple/Elements/RNSVGPattern.mm
apple/Elements/RNSVGRadialGradient.mm
apple/Elements/RNSVGSvgView.mm
apple/Elements/RNSVGSymbol.mm
apple/Elements/RNSVGUse.mm
apple/Shapes/RNSVGCircle.mm
apple/Shapes/RNSVGEllipse.mm
apple/Shapes/RNSVGLine.mm
apple/Shapes/RNSVGRect.mm
apple/Text/RNSVGTSpan.mm
apple/Text/RNSVGText.mm
apple/Text/RNSVGTextPath.mm

PR adding update of `_props` after `updateProps` method in order for e.g. `react-native-reanimated` to pick correct props when running updates. Coauthored by @tomekzaw. It is needed since `RCTMountingManager` reads this field as `oldProps`: https://github.com/facebook/react-native/blob/10e47b891aad8cb1d79a2fccd68edeeefb31756f/React/Fabric/Mounting/RCTMountingManager.mm#L306

feat: update props field so rea works correctly

---

src/ReactNativeSVG.ts

If you built your app using `esbuild` (for example using [`@rnx-kit/metro-serializer-esbuild`](https://microsoft.github.io/rnx-kit/docs/tools/metro-serializer-esbuild)), then it complains that the imports do not exist for type imports.
Marking them explicitely as types fixes this issue, in addition to removing those import/exports from non-TS builds.
I also transformed them from an import + export statements to an `export … from …` statement.
This has been tested in my own app which uses the esbuild serializer mentioned above.
It only changes type exports, so no actual behaviour changes are expected
Having an app using the esbuild serializer
Not relevant
Not relevant

fix: use `export type` when exporting types

---

Example/ios/Podfile.lock
FabricExample/ios/Podfile.lock
src/elements/Svg.tsx

PR fixing the behavior of setting `color` and `tintColor` values on `SvgView` component. Since we added proper annotations and macros on the native side, we don't have to call `processColor` on the JS side. Should fix #1875.

feat: remove processColor so the color is parsed on the native side

---

android/src/main/java/com/horcrux/svg/SvgViewManager.java

Replaces `PointerEvents.parsePointerEvents(pointerEventsStr)` with `PointerEvents.valueOf(pointerEventsStr.toUpperCase(Locale.US).replace("-", "_"))`. This is the implementation of the original method.
Fixes #1890
- Tested debug and release builds of a react-native v0.67.4 project on a physical device. Builds are successful.
- Tested the pointer events prop on the current example and with RN 0.67. Behavior is as expected.

fix: restore compatibility with react-native <0.68 (#1890)

---

Example/babel.config.js
Example/package.json
Example/src/App.tsx
Example/src/examples.tsx
Example/src/examples/Reanimated.tsx
Example/tsconfig.json
Example/webpack.config.js
Example/yarn.lock
src/ReactNativeSVG.web.ts

Up until now, trying to use `reanimated` with `react-native-svg` in `react-native-web` resulted in an error.
This adds a `setNativeProps` function to the web implementation to directly modify the `transform` and `style` props on a SVGElement `ref`.
Since there is a need to track the "last merged props" and those need to be reset on every render, the `render` method has been moved into the `WebShape` class and a `tag` string property has been added.
As `g` had some extra handling for `x` and `y`, a `prepareProps` function was added as well.
Here is a video of me dragging a `<g>` with a nested `<image>` in chome: https://www.loom.com/share/675405537d9d41a792432ebf41636047
Just run any reanimated svg in the browser instead of a device.
Run any animation.
| ------- | …

make reanimated work in web

---

src/ReactNativeSVG.web.ts

Transform prop is ignored on web. This PR stringify transform props so it is compatible with web SVG. It is an extension of https://github.com/react-native-svg/react-native-svg/issues/1824
| iOS     |    no change     |
| Android |    no change    |
| Web |    ✅     |
- [X ] I have tested this on a device and a simulator

Web: Support for transform prop

---

android/src/main/java/com/horcrux/svg/SVGLength.java

`SvgLength` `from` method should be able to parse `null` since it is a correct value, we then use the empty constructor since it provides default values.

fix: handle null passed to SvgLength

---

android/src/main/java/com/horcrux/svg/SvgView.java
android/src/main/java/com/horcrux/svg/VirtualView.java

PR adding handling of `null` values passed to `matrix` and `tintColor` props on `Android`. It should not happen from normal `render` method, but can still be passed with `Animated` or `Reanimated` through native updates or `setNativeProps`. Should fix https://github.com/software-mansion/react-native-svg/issues/1900, https://github.com/software-mansion/react-native-svg/issues/1899.

fix: handle null passed to matrix and tintColor

---

android/src/main/java/com/horcrux/svg/RenderableViewManager.java
android/src/main/java/com/horcrux/svg/SvgPackage.java
android/src/main/java/com/horcrux/svg/SvgViewManager.java
apple/RNSVGRenderableModule.mm
apple/RNSVGSvgViewModule.mm

PR restoring backwards compatibility due to braking changes in method signatures of `getViewManagerNames` and `setHitSlop`, lambda expression being available for RN > 0.64(?). Since `viewRegistry_DEPRECATED` is available from RN 0.65, and its `addUIBlock` method is available from RN 0.69, and both those things are only really needed on new architecture, we use them only there and stick to the old impl for old arch.

fix: make svg compile on older versions

---

.github/workflows/android-build-test.yml
Example/ios/Podfile.lock
Example/package.json
Example/yarn.lock
FabricExample/ios/Podfile.lock
FabricExample/package.json
FabricExample/yarn.lock
TestsExample/ios/Podfile.lock
TestsExample/package.json
TestsExample/yarn.lock

PR bumping example apps to RN `0.70.5` since previous version will cause CI to fail due to bug in RN.

chore: update RN versions to 0.70.5

---

README.md

PR bumping supported RN version for Fabric since it changed due to https://github.com/software-mansion/react-native-svg/pull/1847 having custom cpp state with linking working only from RN `0.70`

chore: bump supported RN version for Fabric

---

windows/RNSVG/RenderableView.cpp
windows/RNSVG/RenderableView.h
windows/RNSVG/SvgView.cpp
windows/RNSVG/SvgView.h
windows/RNSVG/SvgViewManager.cpp
windows/RNSVG/Utils.h
windows/RNSVG/Views.idl

Starting in v13, the switch to Fabric changed the color prop values sent to the native side, so all colors on Windows were defaulting to black. Updated the property setters to handle that change and also added support for the SVG color prop / "currentColor". 
| Windows |    ✅     |

fix: fill/stroke setters and implement currentColor on Windows

---

src/elements/Circle.tsx
src/elements/ClipPath.tsx
src/elements/Defs.tsx
src/elements/Ellipse.tsx
src/elements/ForeignObject.tsx
src/elements/G.tsx
src/elements/Image.tsx
src/elements/Line.tsx
src/elements/LinearGradient.tsx
src/elements/Marker.tsx
src/elements/Mask.tsx
src/elements/Path.tsx
src/elements/Pattern.tsx
src/elements/RadialGradient.tsx
src/elements/Rect.tsx
src/elements/Svg.tsx
src/elements/Symbol.tsx
src/elements/TSpan.tsx
src/elements/Text.tsx
src/elements/TextPath.tsx
src/elements/Use.tsx

When importing the library we have a lot of React Native warning about circular dependency. This PR aims to fix those warnings.

refactor: remove circular dependency

---

src/lib/extract/extractViewBox.ts

PR adding support for comas in viewbox property, replacing them with `space`. Based on work by @HSalaila and @gp3gp3gp3 in https://github.com/software-mansion/react-native-svg/issues/1555. Fixes https://github.com/software-mansion/react-native-svg/issues/1363, fixes https://github.com/software-mansion/react-native-svg/issues/1555.

fix: accept comas in viewbox

---

src/lib/extract/extractFill.ts

PR fixing setting of fill color to black when none is provided to the svg. Regression was most probably introduced in https://github.com/software-mansion/react-native-svg/commit/279c3fcf84540ba12b18dd2056e3189af75c29b4#diff-c9a7ab35811344ee98570618a27ce925792981d9fee1fb77c227b72129363aa6

fix: restore black as a default color for svgs

---

windows/RNSVG/BrushView.cpp
windows/RNSVG/ClipPathView.cpp
windows/RNSVG/ClipPathView.h
windows/RNSVG/ClipPathViewManager.cpp
windows/RNSVG/ClipPathViewManager.h
windows/RNSVG/GroupView.cpp
windows/RNSVG/GroupView.h
windows/RNSVG/GroupViewManager.cpp
windows/RNSVG/ImageView.cpp
windows/RNSVG/PathView.cpp
windows/RNSVG/RNSVG.vcxproj
windows/RNSVG/RNSVG.vcxproj.filters
windows/RNSVG/ReactPackageProvider.cpp
windows/RNSVG/RenderableView.cpp
windows/RNSVG/RenderableView.h
windows/RNSVG/RenderableViewManager.cpp
windows/RNSVG/SvgView.cpp
windows/RNSVG/SvgView.h
windows/RNSVG/SvgViewManager.cpp
windows/RNSVG/SvgViewManager.h
windows/RNSVG/ViewManagers.idl
windows/RNSVG/Views.idl

Adding support for clipPath and touch events. (Closes marlenecota/react-native-svg#6)
https://user-images.githubusercontent.com/1422161/206369981-cd31ea1c-a5f1-4a76-b8c6-6b0e120123d9.mp4
| Windows |    ✅     |

feat(windows): add clipPath and touch events

---

.github/workflows/js-build-test.yml
package.json
yarn.lock

The `.web.js` path in this library currently [breaks tree-shaking in web projects](https://github.com/callstack/react-native-builder-bob/issues/154), causing them to import the entire ~250kb of react-native-web regardless of their other configuration: 
This is because the module build artifacts like `lib/module/ReactNativeSVG.web.js` are in pure ES5 and not ES5+ESM (es5 but preserving import/export statements).
Updating to the latest version of `rn-builder-bob` (which had a prerequisite fix in <https://github.com/callstack/react-native-builder-bob/pull/363> for this library) fixes this, generating the proper ES5+ESM output for the module build (while leaving the commonjs build in pure ES5 with `require`):
This change should only affect the build output and not anything in the native …

Upgrade rn-builder-bob to enable tree-shaking in rn-web

---

apple/Elements/RNSVGSvgView.mm
apple/RNSVGNode.mm

Hi, guys. In recent react-native-macos versions, react-native-svg is broken.
The reason for this is because https://github.com/microsoft/react-native-macos/pull/1612 addressed some of the compiler warnings they were having, one of the being not redefining `opaque` for `NSView`.
Now I see that you have a couple of `#ifdefs` to deal with this already, but the check is not everywhere.
This PR fixes this.
Test latest react-native-macos master with react-native-svg and it will complain that `opaque` is `readonly`.
With this PR, the issue is fixed.
Just using react-native-svg.

Don't set `self.opaque = false` on macOS

---

src/xml.tsx

Fixes https://github.com/software-mansion/react-native-svg/issues/2011
Allows whitespace to be used in the closing tag
See original issue
See original issue

Fix SVG parsing when the closing tags include whitespace

---

android/src/main/java/com/horcrux/svg/RenderableView.java

Currently, there is a bug, that lead to incorrect svg render on android devices. That PR fixes this bug on android.
SVG on android:
SVG on ios and web:
Example component that render incorrectly:
````
import * as React from 'react';
import { SvgXml } from 'react-native-svg';
const xml = `
<svg width="190" height="172" viewBox="0 0 190 172" fill="none" xmlns="http://www.w3.org/2000/svg"><circle cx="96" cy="86" r="79" fill="#FF891D"/><mask id="a" mask-type="alpha" maskUnits="userSpaceOnUse" x="17" y="7" width="158" height="158"><circle cx="96" cy="86" r="79" fill="#fff"/></mask><g mask="url(#a)"><rect x="-13" y="6" width="71" height="32" rx="4" fill="#FFAF65"/><rect x="-13" y="87" width="71" height="32" rx="4" fill="#FFAF65"/><rect x="26" y="46" width="71" height="32" rx="4" …
```

fix: mask render on android

---

Example/src/App.tsx
Example/src/examples.tsx
Example/src/examples/Markers.tsx
android/src/main/java/com/horcrux/svg/CircleView.java
android/src/main/java/com/horcrux/svg/EllipseView.java
android/src/main/java/com/horcrux/svg/GroupView.java
android/src/main/java/com/horcrux/svg/LineView.java
android/src/main/java/com/horcrux/svg/MarkerView.java
android/src/main/java/com/horcrux/svg/RectView.java

#1592
Markers on `Line`, `Rect`, `Ellipse`, `Circle` and `Group`
Markers were only displayed on `Path` on Android. I have looked at the code and `Markers` are based on `elements` attribute which was only filled via `PathParser`. I have modified `getPath` method on other shapes in order to fill `elements` attribute. For groups I only copied data from children. 
Only Android is impacted, markers are now displayed on `Rect`, `Line`, `Ellipse`, `Circle` and `Group` …

fix #1592 : add marker support on Rect, Line, Ellipse, Circle and Group

---

windows/RNSVG/GroupView.cpp
windows/RNSVG/PathView.cpp

I am seeing compile errors on Windows with clang 12.0.1 such as
```
stderr: node_modules\react-native-svg\windows\RNSVG\PathView.cpp:188:10: error: no member named 'isdigit' in namespace 'std'; did you mean simply 'isdigit'?
return std::isdigit(static_cast<unsigned char>(c));
^~~~~~~~~~~~
isdigit
C:\open\fbsource\third-party\toolchains\windows10sdk\10.0.18362.0\Include\10.0.18362.0/ucrt\ctype.h:35:56: note: 'isdigit' declared here
_Check_return_ _CRT_JIT_INTRINSIC _ACRTIMP int __cdecl isdigit(_In_ int _C);
^
node_modules\react-native-svg\windows\RNSVG\PathView.cpp:192:10: error: no member named 'isupper' in namespace 'std'; did you mean simply 'isupper'?
return std::isupper(static_cast<unsigned char>(c));
^~~~~~~~~~~~
isupper
C:\open\fbsource\third-party\toolchains\windows10sdk\10.0.18362. …
```

Fix compilation errors on Windows

---

package.json
src/elements/G.tsx
src/elements/Polygon.tsx
src/elements/Polyline.tsx
src/elements/Shape.tsx
src/elements/Svg.tsx
src/elements/TSpan.tsx
src/elements/Text.tsx

Setting Object to the props type does not allow passing any object to the method. So in TypeScript when using the method for example with Path, you will get an error when passing the d:
```typescript
this.pathComponent?.setNativeProps({ d })
```
```typescript
Argument of type '{ d: string; }' is not assignable to parameter of type 'Object & { matrix?: ColumnMajorTransformMatrix | undefined; fill?: ColorValue | undefined; } & TransformProps'.
Object literal may only specify known properties, and 'd' does not exist in type 'Object & { matrix?: ColumnMajorTransformMatrix | undefined; fill?: ColorValue | undefined; } & TransformProps'
.ts(2345)
```
Instead ob Object, you should use at least P so it allows the original props of the component you are using.
Only Type checking is modified, so it …

Fix setNativeProps type

---

src/ReactNativeSVG.web.ts

Since v13.9.0 `react-native-svg` no longer ships with imports transpiled down to CommonJS. Building a web app with Webpack will now result in this error:
```
ERROR in ./node_modules/react-native-svg/lib/module/ReactNativeSVG.web.js 8:22-24
export 'createElement' (imported as 'cE') was not found in 'react-native' (possible exports: AccessibilityInfo, ActivityIndicator, Alert, Animated, AppRegistry, AppState, Appearance, BackHandler, Button, CheckBox, Clipboard, DeviceEventEmitter, Dimensions, Easing, FlatList, I18nManager, Image, ImageBackground, InteractionManager, Keyboard, KeyboardAvoidingView, LayoutAnimation, Linking, LogBox, Modal, NativeEventEmitter, NativeModules, PanResponder, Picker, PixelRatio, Platform, Pressable, ProgressBar, RefreshControl, SafeAreaView, ScrollView, …
```

fix: remove deprecated import from react-native-web

---

RNSVG.podspec

Fix for #2038. Increased iOS Version which fixes the build. 
Checked the change locally. Also ran `yarn test` without issues. 
Xcode 14.3 is needed for testing.
Build any project using this library. 
Only iOS is affected.

fix: Updating iOS version #2038

---

src/ReactNativeSVG.web.ts
src/lib/resolve.ts

This PR fixes #1920
When `react-native-svg` is used on a web project where typescript has been configured to resolve `.web.ts` file exentions before `.ts`, it causes type errors.
This is because the types in `ReactNativeSVG.web.ts` don't match the types in `ReactNativeSVG.ts`
This PR adds the correct types for all exported components on the web platform inside `ReactNativeSVG.web.ts`. Those changes are:
* Added missing prop types for all components
* Made `style`, `gradientTransform`, and `patternTransform` optional in `BaseProps`.
* Made `styleProp` argument of `resolve()` undefined-able, to support `style` being an optional prop (this also seems to follow the logic in the body of the function, which has a  check for a truthy `styleProp`)
These changes only impact types - no …

fix: make web platform types compatible with native types

---

USAGE.md

`metro.config.js` snippet in `USAGE.md` was outdated, therefore i updated this according the config from `react-native-svg-transformer`.
I left the config for react-native versions prior to 0.72.0 since the syntax changed and people on older versions might appreciate it. #2103

docs: update usage.md for react-native 0.72

---

README.md

Changed expo install react-native-svg to npx expo install react-native-svg, because global expo-cli is deprecated [docs-expo-cli](https://docs.expo.dev/archive/expo-cli/)

docs: Update deprecated expo install instructions to `npx expo install´

---

src/ReactNativeSVG.web.ts

Setting `transform` prop of svg component as `undefined` in web causes the error, so we set it only if the parsed value is not `undefined`.

fix: error for transform on web

---

Example/webpack.config.js

PR fixing web example when using reanimated since `__DEV__` is not defined there.

fix: web not working with reanimated in example

---

android/build.gradle

So that consumer projects don't have to globally enable this themselves leading to performance impact
Since AGP8 this flag is disabled by default. Consumer projects have to enable this flag in them **globally** if the library doesn't do this correctly itself, but uses custom buildConfig fields.
Solves Build Errors with default setup using AGP8+
No errors and better build performance than the workaround in consuming projects would be.
Demonstrate the code is solid. Example: The exact commands you ran and their output, screenshots / videos if the …

enable buildConfig generation to better support AGP8

---

apple/Elements/RNSVGClipPath.mm
apple/Elements/RNSVGForeignObject.mm
apple/Elements/RNSVGGroup.mm
apple/Elements/RNSVGImage.mm
apple/Elements/RNSVGLinearGradient.mm
apple/Elements/RNSVGMarker.mm
apple/Elements/RNSVGMask.mm
apple/Elements/RNSVGPath.mm
apple/Elements/RNSVGPattern.mm
apple/Elements/RNSVGRadialGradient.mm
apple/Elements/RNSVGSvgView.mm
apple/Elements/RNSVGSymbol.mm
apple/Elements/RNSVGUse.mm
apple/Shapes/RNSVGCircle.mm
apple/Shapes/RNSVGEllipse.mm
apple/Shapes/RNSVGLine.mm
apple/Shapes/RNSVGRect.mm
apple/Text/RNSVGTSpan.mm
apple/Text/RNSVGText.mm
apple/Text/RNSVGTextPath.mm
common/cpp/react/renderer/components/rnsvg/RNSVGImageComponentDescriptor.h

Ports the upstream best-practice around props handling of shared_ptr in https://github.com/facebook/react-native/commit/a855013fc6c963aca2282b6b43aeeb621eeb88d7
Build and run the sample app
- [NA] I added documentation in `README.md`
- [NA] I updated the typed files (typescript)
- [NA] I added a test for the API in the `__tests__` folder

perf: avoid unnecessary shared_ptr copies in Fabric components

---

apple/Utils/RNSVGFabricConversions.h

React Native no longer allows implicit copying of Props, since they're large data-structures and copies are often accidental (https://github.com/facebook/react-native/commit/bbc517c8c827a4b4e9191dc7aff3a33c07ee7104). This updates react-native-svg to be compatible with this change, and will provide a small perf win.
Built and run the sample app with the new architecture.
- [NA] I added documentation in `README.md`
- [NA] I updated the typed files (typescript)
- [NA] I added a test for the API in the `__tests__` folder

fix: props are no longer unnecesarily copied in new architecture

---

RNSVG.podspec
android/src/main/jni/CMakeLists.txt

RN 0.73 adds the requirement that ComponentViews, ShadowNodws, etc, build using C++ 20. This adds the flags to do that when building for Android.
Locally validated this does not prevent us from building earlier RN Fabric (at least 0.72), by changing the flags in CMakeLists.txt, then running `./gradlew assembleDebug` in `FabricExample`.
I think RN on iOS will set C++ version for you [during pod install](https://github.com/facebook/react-native/commit/ca8174e15f77cbeecb7ff7a5a583abb668817777).

Build `renderer/components/rnsvg` with `-std=c++20`

---

.eslintrc.js
Example/metro.config.js
FabricExample/metro.config.js
TestsExample/metro.config.js
TestsExample/src/Test1813.tsx
USAGE.md
__tests__/css.test.tsx
css/package.json
package.json
src/ReactNativeSVG.ts
src/css/LocalSvg.tsx
src/css/css.tsx
src/css/index.tsx
src/deprecated.tsx
tsconfig.json

PR based on https://github.com/software-mansion/react-native-svg/pull/1452 extracting `css` related components to different package to reduce the size of the package.
***THIS IS A BREAKING CHANGE***. From now on, you should import 
```
SvgCss,
SvgCssUri,
SvgWithCss,
SvgWithCssUri,
inlineStyles,
LocalSvg,
WithLocalSvg,
loadLocalRawResource,
```
from `react-native-svg/css` package instead.

feat: move css to different package for size reduction

---

FabricExample/ios/Podfile.lock
apple/Elements/RNSVGImage.mm

PR removing the unused header in `Image` component causing problems mentioned in https://github.com/software-mansion/react-native-svg/issues/2082 and https://github.com/software-mansion/react-native-svg/issues/2154.
Try and build FabricExample app.

fix: remove unused header causing problems

---

src/css/css.tsx

When using the `SvgCssUri` component, specifying `fallback` does not render the fallback component in the case of an error.
I looked through the source code and believe this is because `SvgCssUri` is rendering a `SvgCss`
https://github.com/software-mansion/react-native-svg/blob/22f47333fbe134b0c697b9c0190a09d6927f2cea/src/css.tsx#L712
which renders a `SvgAst`
https://github.com/software-mansion/react-native-svg/blob/22f47333fbe134b0c697b9c0190a09d6927f2cea/src/css.tsx#L696
which does not use the `fallback` prop
https://github.com/software-mansion/react-native-svg/blob/22f47333fbe134b0c697b9c0190a09d6927f2cea/src/xml.tsx#L96
This fix copies over the error handling code from `SvgUri` so `SvgCssUri` can render a fallback on error. I tested the change in my project and this works like it does …

fix `SvgCssUri` fallback

---

windows/RNSVG/SvgView.cpp

There are many reasons `Loaded` can fire twice. Usually, it will happen when the native SvgView component is moved, but it can also happen if an ancestor of SvgView is reparented. There is a crash that appears to occur when we attempt to call CreateResources twice. This resolves that crash.
Windows
Ran a sample that appears to cause the SvgView to load twice. Without this change, the app crashes. With this change, the app no longer crashes.

Minor fix to prevent crash when Loaded fires twice

---

RNSVG.podspec
apple/RNSVGRenderable.mm

This PR adds support for visionOS. I've migrated the `UIScreen` API to take `displayScale` from `currentTraitCollection` - same as I did in Core (https://github.com/facebook/react-native/pull/41214/files) 
1. Init new app with `npx @callstack/react-native-visionos init TestApp` 
2. `yarn add react-native-svg`
3. Install pods
4. Check if the app compiles 
Xcode 15.1 Beta
Build the app

feat: add visionOS support

---

src/lib/extract/extractTransform.ts

Type TransformsStyle['transform'] has `string` added as option from React Native 0.71.9 onward. This breaks the logic of `transformsArrayToProps`.
This PR fixes this by scoping down the type, and removing a no-op usage of `transformsArrayToProps`
This has been broken for a while, but not immediately visible to users compiling using Metro and Babel.
This should fix #2135 .
(PR seems to have gotten a bit of clutter from the `git commit` hook removing trailing commas as well).

fix: Correct types for transformsArrayToProps

---

src/ReactNativeSVG.ts
tsconfig.json

This is the same issue as the one I fixed last year in #1874
To prevent this from occurring again, I enabled the `isolatedModules` Typescript option which will warn when you export non-value identifiers without using `export type`, which will break transpilation processes what work on a per-file basis. You can find a [more detailed explanation in Typescript's doc](https://www.typescriptlang.org/tsconfig#isolatedModules)
I used this patch in my own app using [@rnx-kit/metro-serializer-esbuild](https://microsoft.github.io/rnx-kit/docs/tools/metro-serializer-esbuild) and it builds correctly. The preview version was already using `export type` without any reported issues.
Not relevant
Not relevant

Fix type exports and enable `isolatedModules` setting to catch it in `tsc`

---

windows/RNSVG/GroupViewManager.cpp
windows/RNSVG/RenderableView.cpp
windows/RNSVG/RenderableView.h
windows/RNSVG/Views.idl

XAML may unload the root SVG panel, which will trigger a recursive unload. For GroupView, this unload will clear the child collection. However, active operations on the SVG from the React Native UIManager may still be in flight, in which case we may attempt to remove a child that has already been cleared by the root unload.
This wouldn't repro in any of the existing examples, but the crash no longer occurs in our app.

Fix crash when SVG is unloaded by XAML

---

TestsExample/App.js
TestsExample/src/Test2196.tsx
src/css/css.tsx

This crash issue still happening for SvgCssUri component
https://github.com/software-mansion/react-native-svg/issues/1760
Apply similar fix https://github.com/software-mansion/react-native-svg/pull/2071
specifically for SvgCSSUri component to prevent crashes due to invalid svg content
-> When loading invalid svg uri with SvgCSSUri, the app crashes crashes. For example the content returning html content instead of valid svg content.
-> Passing the fallback prop to SvgCss where will be render when error being captured
SvgCss and SvgUriCss
Tested manually: 
- first using invalid svg file …

fix(SvgCssUri): support rendering fallback instead of crashing the app when loading invalid content from remote svg file

---

windows/RNSVG.sln
windows/RNSVG/RNSVG.rc
windows/RNSVG/RNSVG.vcxproj
windows/RNSVG/RNSVG.vcxproj.filters
windows/RNSVG/resource.h
windows/RNSVG/versionoverrides.rc

On Windows, `RNSVG.dll` is getting flagged by AppLocker on many of our user's devices because it is missing proper publisher/versioning information in its metadata. This forces users to manually add this DLL to AppLocker's allow-list during some update/installation scenarios.
The `RNSVG.sln` file also currently fails to build from Visual Studio directly, because the `fmt` project is not explicitly included from the `react-native-windows` Node package.
For testing, I opened `RNSVG.sln` in Visual Studio on Windows (with Node packages installed and other build prerequisites) and built it for `Debug|x64`.
Without my change, building the solution fails to build directly from Visual Studio (since it fails to link fmt.lib when building the Microsoft.ReactNative project). Even when building from …

fix: Ensure RNSVG.dll is built with proper publisher/versioning information via new resource file.

---

RNSVG.podspec

This PR fixes the following errors when compiling for visionOS:
`Unknown type name 'NSColor'`

fix: visionOS support

---

android/src/main/java/com/horcrux/svg/RNSVGRenderableManager.java

fixed warning in React Native 0.73: 'com.facebook.react.common.StandardCharsets' is deprecated and marked for removal
**com.facebook.react.common.StandardCharsets** was marked as `@Deprecated`, and says "Deprecated class since v0.73.0, please use java.nio.charset.StandardCharsets instead."
RNSVGRenderableManager.java
```java
// react-native-svg/android/src/main/java/com/horcrux/svg/RNSVGRenderableManager.java
// replace this line 
import static com.facebook.react.common.StandardCharsets.UTF_8;
// with
import static java.nio.charset.StandardCharsets.UTF_8;
```
It doesn't make any break changes because they are the same value: `Charset.forName("UTF-8")`

fixed @Deprecated warning in React Native 0.73: 'com.facebook.react.common.StandardCharsets' is deprecated and marked for removal

---

src/css/LocalSvg.tsx

Our sentry
This PR fixes typo on require statement.
It makes `WithLocalSvg` function as expected without crash.
`import { WithLocalSvg } from 'react-native-svg/css'`
Nothing

fix: typo on require statement (`WithLocalSvg`)

---

Example/ios/Podfile.lock
apple/RNSVGRenderable.mm

This PR adds missing checks whether SVG bounds size values are nan. This PR should fix [this](https://github.com/software-mansion/react-native-svg/issues/978) old issue that still happens sometimes.
I was unable to reproduce the issue on my device but we got multiple issue reports on Sentry in the production environment. Here is the stacktrace based on which I implemented this fix.

fix: Add missing nan value checks for bounds size

---

windows/RNSVG/D2DHelpers.h
windows/RNSVG/GroupViewManager.cpp
windows/RNSVG/GroupViewManager.h
windows/RNSVG/RenderableView.cpp
windows/RNSVG/RenderableView.h
windows/RNSVG/RenderableViewManager.cpp
windows/RNSVG/RenderableViewManager.h
windows/RNSVG/SvgView.cpp
windows/RNSVG/SvgView.h
windows/RNSVG/SvgViewManager.cpp
windows/RNSVG/SvgViewManager.h
windows/RNSVG/Utils.h
windows/RNSVG/Views.idl
windows/RNSVG/pch.h

Adds namespace redirects required to compile react-native-svg sources against WinAppSDK for react-native-windows.
There aren't a lot of examples for building react-native-windows apps in open source targeting WinAppSDK, but we have some proprietary builds, and this source code is working there (it is also still compatible with UWP).

Adds support to compile react-native-svg against WinAppSDK

---

TestsExample/App.js
TestsExample/src/Test2266.tsx
android/src/main/java/com/horcrux/svg/RenderableView.java

According to [MDN Docs](https://developer.mozilla.org/en-US/docs/Web/SVG/Attribute/stroke-width), when `strokeWidth` is not provided, the default value should be set to `1`.
On android, when we update the `strokeWidth` prop to `undefined` it was mistakenly converted to `0` by `SVGLength`. 
Fixes #2266 
Test available in `TestsExample/Test2266` 
* Run `TestsExample` app
* Replace `ColorTest` with `Test2266` in `App.js`

fix: set default strokeWidth to 1 on android

---

RNSVG.podspec

On Cocoapods versions of lower than 1.14.3, pod install fails due to it not understanding the visionos field.
Our company cannot use a higher version of Cocoapods right now, so it would be beneficial if we or other similar people can use the latest version of react-native-svg without having to upgrade the Cocoapods version.
I was able to find this solution from https://github.com/getsentry/sentry-react-native/issues/3547#issuecomment-1907677879

fix: Fix pod install not working with lower version of Cocoapods due to visionOS

---

android/src/main/java/com/horcrux/svg/SvgViewManager.java
android/src/paper/java/com/facebook/react/viewmanagers/RNSVGSvgViewAndroidManagerDelegate.java
android/src/paper/java/com/facebook/react/viewmanagers/RNSVGSvgViewAndroidManagerInterface.java
src/fabric/AndroidSvgViewNativeComponent.ts

As per title, when running an app in bridgless mode the following redbox appears:
> StaticViewConfigValidator: Invalid static view config for 'RNSVGSvgViewAndroid'.
> 
> 'validAttributes.borderBlockColor' is missing.
> 'validAttributes.borderBlockEndColor' is missing.
> 'validAttributes.borderBlockStartColor' is missing.
> 'validAttributes.borderEndEndRadius' is missing.
> 'validAttributes.borderEndStartRadius' is missing.
> 'validAttributes.borderStartEndRadius' is missing.
> 'validAttributes.borderStartStartRadius' is missing.
Tested that the redbox is gone.
| iOS     |    N/A     |

fix: Fix static view config validation for RNSVGSvgViewAndroid

---

TestsExample/src/Test2170.tsx
android/src/main/java/com/horcrux/svg/Brush.java
apple/Brushes/RNSVGPainter.mm

* Fixed crash on Android when `<RadialGradient r={0}>`.
* Fixed render issue on Android and iOS when radius is zero. According to [MDN Docs](https://developer.mozilla.org/en-US/docs/Web/SVG/Attribute/r#radialgradient)
> A value of lower or equal to zero will cause the area to be painted as a single color using the color and opacity of the last gradient `<stop>`.
Test is available in `TestsExample` as `Test2170`
| iOS     |    ✅    |
Fixes #2170

fix: radialGradient `r={0}`

---

TestsExample/App.js
TestsExample/src/Test2276.tsx
src/xml.tsx

When comment occurred before first tag, there was a possible parsing error if it contains `<` character.
Here is an example (line 2 and 3 would cause separate errors):
```xml
<svg width="200" height="200" xmlns="http://www.w3.org/2000/svg">
<rect width="100" height="100" x="50" y="50" fill="red" />
</svg>
```
Fixes #2276
Manual tests in `TestsExample` app. (Test2276)

fix: parsing `<` inside comments

---

android/build.gradle

We had similar config in react-native-screens. It caused problem when building Paper arch app after Fabric. Those changes help, so I'm moving them here as well.

fix: error when building paper after fabric

---

TestsExample/metro.config.js
TestsExample/package.json
TestsExample/yarn.lock

We want to fix the TextExample app
- change version of react-native-reanimated.
- add to `metro.config.js` extraNodeModules: 
```
'react-native-svg': `${__dirname}/../`
```
test manually.

chore: TestsExample app fix reanimated and metro.config issues

---

src/ReactNativeSVG.web.ts

Closes #1483
Closes #1524
We want a handle `onPress` prop on the web version in SVG components.
Check on `react-native` web version if prop onPress works.
| Web     |    ✅     |

fix: handle onPress prop on web app

---

TestsExample/App.js
TestsExample/src/Test2086.tsx
android/src/main/java/com/horcrux/svg/PathParser.java

Closes #2086
The application crashes if an error is thrown when something goes wrong during path parse.
You can easily check in that component `Test2086` how it works after the fix.

fix: android PathParser crash app if pass some wrong d prop

---

TestsExample/App.js
TestsExample/src/MountUnmount.tsx
apple/RNSVGNode.mm

On iOS with the new architecture, when mounting or unmounting a component, changes were not visible because `invalidate` wasn't called. These changes override `mountChildComponentView` and `unmountChildComponentView` to ensure that invalidate is called when `RNSVGNode` is mounted or unmounted.
`TestExample` app -> `MountUnmount` example 
```tsx
import React from 'react';
import {Button, Text, View} from 'react-native';
import {Rect, Svg} from 'react-native-svg';
export default () => {
const [show, setShow] = React.useState(true);
return (
<View style={{flex: 1, justifyContent: 'center', alignItems: 'center'}}>
<Text>Blue rect is mounted: {show ? 'true' : 'false'}</Text>
<Svg height="300" width="300">
{show ? (
<Rect x="100" y="100" width="100" height="100" fill="blue" />
) : null}
</Svg> …
```

fix: new arch invalidate on mount/unmount

---

apple/Elements/RNSVGImage.mm

We have to merge those changes to that [PR](https://github.com/software-mansion/react-native-svg/pull/2319) and check the pipeline in the macos platform.

fix: add check  in RNSVGImage for macos platform

---

src/elements/Svg.tsx
src/lib/extract/extractOpacity.ts

According to the MDN Docs `opacity` as a `<alpha-value>` can be represented as
> A [<number>](https://developer.mozilla.org/en-US/docs/Web/CSS/number) in the range 0.0 to 1.0, inclusive, or a [<percentage>](https://developer.mozilla.org/en-US/docs/Web/CSS/percentage) in the range 0% to 100%, inclusive, representing the opacity of the channel (that is, the value of its alpha channel). Any value outside the interval, though valid, is clamped to the nearest limit in the range.
https://developer.mozilla.org/en-US/docs/Web/CSS/opacity#alpha-value
https://developer.mozilla.org/en-US/docs/Web/SVG/Attribute/fill-opacity#usage_notes

fix: extract opacity use percentage values

---

apple/RNSVGRenderable.mm

Fixed regression introduced in #2299. Now `<Mask>` is rendering properly on MacOS.
* `Test1451` in `TestsExample`
* Masking section in `example`
https://github.com/software-mansion/react-native-svg/assets/39670088/dccc937d-125d-4b60-864b-cc3b9a4179fb
| macOS     |    ✅     |

fix: macos mask

---

common/cpp/react/renderer/components/rnsvg/RNSVGImageState.h

Currently, react-native-svg fails to compile on Android with `react-native@0.75.0-rc.4` and new architecture enabled due to an unknown identified `folly::dynamic`.
This PR adds the missing import so that the identifier has a declaration.
I've already tested out this change in Reanimated's fabric-example app.

Add missing `#import <folly/dynamic.h>` on RN 0.75

---

android/src/main/java/com/horcrux/svg/FilterView.java

Closes #2347
Fixed a problem with building an Android app, pattern matching threw an error when we tried to build an Android app.
[Repository](https://github.com/bohdanprog/react-native-svg-error-pattern-matching) to reproduce that error.
We can easily check that build the app.
build the app without that fix.

fix: remove using pattern matching in FilterView

---

src/elements/Svg.tsx

Fix bug introduced in #2189, 
if `style` is not provided, then `StyleSheet.flatten` returns `undefined`, and we're trying to access `transform` of it.
Run `example` app

fix: cannot set property transform of undefined (gStyle)

---

apple/Elements/RNSVGSvgView.h
apple/Elements/RNSVGSvgView.mm
apple/RNSVGRenderable.mm

Closes #2356
Currently, when `filter` prop is defined, but there is no equivalent `<Filter>` component, on iOS nothing is rendered, with this fix this prop would be ignored, and the component should render as expected.
```tsx
<Svg width="400" height="400" viewBox="0 0 124 124" fill="none">
<Rect width="124" height="124" rx="24" fill="red" filter="url(#nonExistingFilterId)"/>
</Svg>
```

fix: ignore invalid filter id

---

android/src/main/java/com/horcrux/svg/FeColorMatrixView.java

While debugging #2364 I've noticed that color shift in `FeColorMatrix` on Android is wrong.
On web, elements 5, 10, 15, 20 is a color shift represented by number where 1 mean full color shift, while on Android it's 255 for full color shift.
```tsx
<svg width="180" height="180" viewBox="0 0 180 180">
<rect width="180" height="180" fill="red" filter="url(#filter)"/>
<filter id="filter">
<feColorMatrix type="matrix" values="0 0 0 0 1
0 1 0 0 0
0 0 1 0 0
0 0 0 1 0"/>
</filter>
</svg>
```

fix: color shift in FeColorMatrix on android

---

apple/Filters/RNSVGFilter.mm
apps/test-examples/App.js
apps/test-examples/src/Test2366.tsx

Applying multiple `FeColorFilter` instances can cause unexpected behavior on iOS, likely due to a bug in `CoreImage` where the `CIImage` recipe isn't applied step by step as it should be. This fix ensures that the filter result is rendered after each application by converting the image to `CGImage` and then back to `CIImage`.
With this simple test, we can prove that these changes are working
```tsx
<Svg height="200" width="200">
<Filter id="filter">
<FeColorMatrix type="matrix" values="78 -70 -7 0 0 -21 29 -7 0 0 -21 -70 0 0 0 0 0 0 1 0"/>
<FeColorMatrix type="matrix" values="0.2126, 0.7152, 0.0722, 0, 0, 0.2126, 0.7152, 0.0722, 0, 0, 0.2126, 0.7152, 0, 0, 0, 0, 0, 0, 1, 0"/>
</Filter>
<Rect width="200" height="200" fill="red" filter="url(#filter)"/>
</Svg>
```
| Web | iOS before changes …

fix: applying multiple filters on iOS

---

android/src/main/jni/CMakeLists.txt

feat: Make CMake less verbose

---

android/src/main/java/com/horcrux/svg/FeMergeView.java
apple/Filters/RNSVGFeMerge.mm
src/fabric/FeMergeNativeComponent.ts
src/lib/extract/extractFilter.ts

Use empty string (`""`) instead of `undefined` for previous filter result in `FeMergeNode`

fix: FeMerge on paper

---

src/filter-image/FilterImage.tsx

Small fix to destruct filter from style prop before passing down styles to View.

fix: `FilterImage` css filter on web

---

src/filter-image/FilterImage.tsx

Somehow deconstructing `filter` from `styles` are throwing error, when filter does not exist. These changes ensure that `filter` is always there (`[]` if not exists).

fix: deconstruct filter from styles

---

package.json

Fix pre-commit `format-js` prettier error caused by https://github.com/software-mansion/react-native-svg/pull/2408

chore: fix prettier

---

src/web/utils/prepare.ts

Do not resolve asset url for every object when href is undefined on WebShape.

fix: do not resolve asset url for every object on web.

---

apple/Elements/RNSVGSvgView.mm

Since `RNSVGPlatformView` on macOS old arch is just `RCTUIView`, we need to add `updateReactTransformInternal` to `RNSVGSvgView`.

fix: transforms on macOS old arch

---

android/src/main/java/com/horcrux/svg/SvgView.java

Fixes #2421, bug introduced in https://github.com/software-mansion/react-native-svg/pull/2403/files#diff-7f8adeb6e7faded1a7ef711b4fa9d2b12d29ff386217e838c4551866afdd8befR286 this line. When bitmap size is less or equal to 0 we want to stop rendering the SVG to avoid Android crash.
Set `transform="scale(0)"` to `Svg` element.

fix: android svg scale 0

---

android/src/main/java/com/horcrux/svg/SvgView.java

Fixes #2436.
#2403 introduced shared `Paint` between the node render method and the final bitmap. However, Paint properties are not cleared after drawing, so we need to call the `.clear()` method and re-enable antialiasing.

fix: reset paint settings before drawing final bitmap

---

USAGE.md

Short explanation on how to configure the webpack bundler and a brief rationale on why it's preferable to use the Metro bundler.

docs: introduce about webpack and metro bundler

---

README.md

- simple fix for the example link in the root readme of the project
- removed todo link as it's not exist anymore in the readme

docs: broken link in the readme file

---

android/src/main/java/com/horcrux/svg/GroupView.java
apps/test-examples/index.tsx
apps/test-examples/src/Test2417.tsx

Currently, on Android, when the `opacity` prop is applied to `G` or `Svg` elements, it is rendered incorrectly. Instead of rendering the children "offscreen" and then applying the opacity to the entire result, the child elements themselves are rendered with the specified opacity.
Fixes #2046
```tsx
import {View} from 'react-native';
import {G, Rect, Svg} from 'react-native-svg';
export default function App() {
return (
<View style={{flex: 1, justifyContent: 'center', alignItems: 'center'}}>
<Svg width="150" height="150" viewBox="0 0 150 150">
<G opacity="0.5">
<Rect width="100" height="100" fill="red" />
<Rect x="50" y="50" width="100" height="100" fill="green" />
</G>
</Svg>
<Svg width="150" height="150" viewBox="0 0 150 150" opacity="0.5">
<Rect width="100" height="100" fill="red" /> …
```

fix: Android group `opacity` prop

---

android/src/main/java/com/horcrux/svg/GroupView.java

Improve #2417 by applying offscreen canvas only when opacity attribute is set

fix: render G offscreen only when it's needed (opacity != 1)

---

tsconfig.json

Hot fix for #2453 missing types.
Closes #2453.

fix: exclude e2e from types in release

---

android/src/main/java/com/horcrux/svg/RenderableView.java

On Android when element before masked element has strokeOpacity different from 1, the paint is reused to draw an offscreen layer resulting in wrong opacity. Partially fixes (only on Android) #2449 
Add `stroke` and `strokeOpacity` to element directly before masked element.

fix: masked element layer opacity when previous item has stroke opacity

---

apple/Elements/RNSVGSvgView.mm
apps/test-examples/index.tsx
apps/test-examples/src/Test2455.tsx

Fixes #2455. When the shared modal was triggered, the `currentColor` (which is `tintColor` under the hood) was being greyscaled because the default value of `tintAdjustmentMode` was set to `UIViewTintAdjustmentModeDimmed`. Changing it to `UIViewTintAdjustmentModeNormal` resolves the issue.
Example apps -> `Test2455`

fix: currentColor dimming

---

.github/workflows/ios-build-test.yml
.github/workflows/ios-e2e.yml
.github/workflows/macos-build-test-fabric.yml
.github/workflows/macos-build-test-paper.yml

chore: update iOS workflows

---

android/src/main/java/com/horcrux/svg/FilterPrimitiveView.java
android/src/main/java/com/horcrux/svg/FilterRegion.java
android/src/main/java/com/horcrux/svg/FilterView.java
apple/Filters/RNSVGFilter.h
apple/Filters/RNSVGFilter.mm
apple/Filters/RNSVGFilterPrimitive.h
apple/Filters/RNSVGFilterPrimitive.mm
apple/Filters/RNSVGFilterRegion.h
apple/Filters/RNSVGFilterRegion.mm
apple/RNSVGNode.h

[apple] Use filter region directly instead of creating new one on every rerender.
[android] rename some variables and add temporary fix for null lengths

feat: implement filter region lengths directly on RNSVGFilterRegion

---

android/src/main/java/com/horcrux/svg/FilterRegion.java
android/src/main/java/com/horcrux/svg/FilterView.java
apple/Filters/RNSVGFilter.mm
apple/Filters/RNSVGFilterRegion.mm
src/elements/filters/FilterPrimitive.tsx

After deep dive into the specification, I found out that the default filter subregion is not equal to `0% 0% 100% 100%`, rather the size of the parent filter region.

feat: properly implement filter region unit USER_SPACE_ON_USE

---

apple/Filters/RNSVGFilter.mm
apple/Filters/RNSVGFilterPrimitive.mm

Filter regions were nil as init is not called when view is reused.

fix: do not remove filter region on recycle

---

android/src/main/java/com/horcrux/svg/FilterRegion.java
android/src/main/java/com/horcrux/svg/FilterView.java

This fix addresses a minor bug/typo that was recently introduced, where the filter subregion was incorrectly relying on filterUnits instead of primitiveUnits.

fix: filter subregion depend on primitive units not filter units

---

android/src/main/java/com/horcrux/svg/FilterRegion.java
apps/examples/src/examples/Filters/FeFlood.tsx

Do not crash on `getCropRect` call when renderableBounds is null

fix: crop rect invalid bounds crash 

---

README.md

`react-native-svg@15.8.0` requires `react-native@0.73.0+` or above.

docs: add entry to supported react-native version

---

src/index.ts

Add basic support for React Server Components support. This package could surely be improved (at least on web) but there are a lot of class components (unsupported in RSC) which need to be rewritten to function components in order to compile down further. For now, I'm opting the entire package. 
Related PRs for more context:
- https://github.com/necolas/react-native-web/pull/2678
- https://github.com/th3rdwave/react-native-safe-area-context/pull/502
- I've added more support for mixing export types, but it isn't perfect https://github.com/expo/expo/pull/29426
- It's kinda hard to test this E2E. I wrote a small jest runner in jest-expo which executes in RSC mode, but it requires React 19 to work. Here's where I tested this patch https://github.com/expo/expo/pull/29404

feat: add basic React Server Component support

---

apple/Elements/RNSVGGroup.mm
apple/Elements/RNSVGSvgView.h
apple/Elements/RNSVGSvgView.mm

Continuation of #2136, specifically for percentage values, images and this: https://github.com/software-mansion/react-native-svg/pull/2136#discussion_r1332222783
| before | after |
| --- | --- |
| <img width="1392" alt="Zrzut ekranu 2024-10-21 o 12 07 46" src="https://github.com/user-attachments/assets/8903e069-d700-449d-ab7a-3a866f362c62"> | <img width="1392" alt="Zrzut ekranu 2024-10-21 o 12 09 16" src="https://github.com/user-attachments/assets/2a166d73-9082-4d40-af1e-c945400cb56c"> |
| <img width="1392" alt="Zrzut ekranu 2024-10-21 o 12 07 41" src="https://github.com/user-attachments/assets/ee2c6c22-ba3f-47f4-a0c4-1864c94e4953"> | <img width="1392" alt="Zrzut ekranu 2024-10-21 o 12 09 09" src="https://github.com/user-attachments/assets/2c5bdff5-5ef4-4cae-bfc6-dcdc9d532070"> |
Run …

fix: macOS percentage values and images

---

apps/fabric-example/metro.config.js
apps/fabric-macos-example/metro.config.js
apps/fabric-windows-example/metro.config.js
apps/paper-macos-example/metro.config.js
apps/paper-windows-example/metro.config.js
apps/tests-example/metro.config.js
apps/web-example/metro.config.js

fix: example apps metro paths

---

USAGE.md
apps/common/example/examples/Filters/FeDropShadow.tsx
apps/common/example/examples/Filters/index.tsx
src/elements/filters/FeDropShadow.tsx

Continuation of #2362 introducing highly requested ✨ `FeDropShadow`  ✨ filter. This addition is straightforward since it's essentially a shorthand (as specified in the spec) for filters that are already implemented: https://www.w3.org/TR/filter-effects-1/#feDropShadowElement
Example app -> Filters -> FeDropShadow
| macOS   |    ✅      |
| Web     |    ✅      |

feat: FeDropShadow

---

android/src/main/java/com/horcrux/svg/FeOffsetView.java

While working on #2514 I've noticed that negative dx/dy were treated as positive.
Add FeOffset filter with negative dx/dy to an element. It should move closer to upper left corner.

fix: negative dx/dy in feOffset

---

android/src/main/java/com/horcrux/svg/FeCompositeView.java

While working on https://github.com/software-mansion/react-native-svg/pull/2514 I've noticed a bug in `FeComposite` on Android that `in2` was ignored 
Run Example app -> filters -> FeComposite on Android

fix: FeComposite in2 on Android

---

apps/common/example/examples/Empty.tsx
apps/common/example/examples/Filters/FeDropShadow.tsx
apps/common/example/examples/index.tsx

Create Empty screen with blank svg in example app as playground
Additionally add FeDropShadow icon as i forgot about it.

docs: add Empty screen as playground

---

apps/common/test/PointerEventsBoxNone.tsx
apps/common/test/Test1374.tsx
apps/common/test/Test1442.tsx
apps/common/test/Test1718.tsx
apps/common/test/Test1813.tsx
apps/common/test/Test1845.tsx
apps/common/test/Test2080.tsx
apps/common/test/Test2086.tsx
apps/common/test/Test2089.tsx
apps/common/test/Test2196.tsx
apps/common/test/Test2248.tsx
apps/common/test/Test2327.tsx
apps/common/test/Test2363.tsx
apps/common/test/Test2397.tsx
apps/common/test/Test2455.tsx
apps/web-example/package.json
apps/web-example/yarn.lock

A minor change in web example app to fix SVG path and reformat examples with prettier/lint

chore: fix web-example app path and format examples

---

src/lib/util.ts

Closes #2523
Since `FeBlend`, `FeComposite`, `FeDropShadow` and `FeFlood` is already supported (see: #2362) we should remove it from `warnUnimplementedFilter` list

fix: update warnUnimplementedFilter list

---

apple/Elements/RNSVGForeignObject.mm
apple/Elements/RNSVGGroup.mm
apple/RNSVGRenderable.mm
apple/RNSVGRenderableModule.mm

As per the spec, bbox should not include any transformations, including scaling. It should also not include any control points. This fixes getBBox to give correct results matching Google Chrome, Firefox as per the spec.
Bug fix.
Like this, see.
getBBox API.
I build some stuff that works with SVG, the results on web were inconsistent, and digging down I realise it was a react-native-svg.
Some fun fact, there was a surprisingly similar bug related to very confusing named (CGPathGetBoundingBox vs CGPathGetPathBoundingBox) APIs in Firefox some years …

fix: apple bounding box (CGPathGetPathBoundingBox)

---

src/elements/filters/FeBlend.tsx

Fixes #2529
`FeBlend` should have default blend mode set to `normal`
Test case specified in #2529

fix: add default FeBlend mode

---

apple/Filters/RNSVGFilter.mm

While animating filters, I discovered a memory leak due to not releasing the `CGImage` after creating the mask.
```tsx
import {useEffect} from 'react';
import Animated, { useSharedValue, withRepeat, withTiming } from 'react-native-reanimated';
import Svg, {FeOffset, Filter, Rect} from 'react-native-svg';
const AnimatedFilter = Animated.createAnimatedComponent(Filter);
const AnimatedFeOffset = Animated.createAnimatedComponent(FeOffset);
const AnimatedRect = Animated.createAnimatedComponent(Rect);
export default function Example() {
const offset = useSharedValue(0.5);
useEffect(() => {
offset.value = withRepeat(withTiming(300, {duration: 3000}), -1, true);
}, []);
return (
<Svg height="300" width="300">
<AnimatedFilter id="filter">
<AnimatedFeOffset dx={offset} dy={offset} result="offOut" …
```

fix: filters memory leak on apple

---

apple/Utils/RCTConvert+RNSVG.mm
apple/Utils/RNSVGFabricConversions.h

Closes #2535
When `fill` or `stroke` is set to `'none'` we should remove the value instead of keeping the last valid value.
```tsx
import React, {useState} from 'react';
import {Text, TouchableOpacity} from 'react-native';
import {Path, Rect, Svg} from 'react-native-svg';
function Example() {
const [color, setColor] = useState('#0000FF');
return (
<>
<Svg width={120} height={150} viewBox="0 0 12 15" fill="none">
<Path
d="M1 3.353C1 2.053 2.053 1 3.353 1H8.647C9.947 1 11 2.053 11 3.353V13.207C11 13.3008 10.9736 13.3927 10.9238 13.4722C10.874 13.5518 10.8029 13.6157 10.7185 13.6567C10.6341 13.6976 10.5399 13.7141 10.4466 13.7041C10.3533 13.694 10.2648 13.658 10.191 13.6L7.202 11.25C6.99452 11.0876 6.7385 10.9995 6.475 11H3.353C2.72895 11 2.13045 10.7521 1.68918 10.3108C1.2479 9.86955 1 …
```

fix: remove fill and stroke when its unset

---

apps/paper-macos-example/macos/PaperMacOSExample.xcodeproj/project.pbxproj
apps/paper-macos-example/macos/Podfile.lock

Regenerate pods to fix `paper-macos-example` workflow. `fabric-macos-example` will still fail as it doesn't have any startup command, but it's not our fault.
CI for `peper-macos-example` should be green

chore: fix paper-macos-example workflow

---

android/src/main/java/com/horcrux/svg/SvgPackage.java

Address some deprecated API's in SVGPackage
This improves compatibility with future React Native releases, which will remove TurboReactPackage and the ReactModuleInfo constructor used.
CI

feat: update SvgPackage to supported stable API's

---

apple/RNSVGNode.mm
apple/Utils/RNSVGFabricConversions.h
apple/ViewManagers/RNSVGNodeManager.mm

Add `resolveTransforms` on `updateProps` to get correct matrix. It will improve animating transformations, as Animated/Reanimated skips JS `processTransform` and passes transformations directly. 
Animate `transform` prop in react-native style.

fix: resolve transforms on new architecture

---

android/src/main/java/com/horcrux/svg/GroupView.java
android/src/main/java/com/horcrux/svg/RenderableView.java
android/src/main/java/com/horcrux/svg/RenderableViewManager.java
android/src/main/java/com/horcrux/svg/TSpanView.java
android/src/main/java/com/horcrux/svg/UseView.java
android/src/main/java/com/horcrux/svg/VirtualView.java
apple/Elements/RNSVGForeignObject.mm
apple/Elements/RNSVGGroup.mm
apple/Elements/RNSVGImage.mm
apple/Elements/RNSVGUse.mm
apple/RNSVGNode.h
apple/RNSVGNode.mm
apple/RNSVGRenderable.mm
apple/Utils/RNSVGFabricConversions.h
apple/ViewManagers/RNSVGNodeManager.mm

When using the Animated API for animations, it sends the last frame as JavaScript-parsed (matrix) updates in addition to native (transform) updates. ~~As a result, we need to ignore one of them.~~ I believe there's no need to differentiate between native and JavaScript updates—we can simply save both to the same value (mMatrix). By doing so, we can avoid duplicating the transforms.
| Before | After |
|--------|--------|
| <video src="https://github.com/user-attachments/assets/868cc778-4b88-4473-85b5-9665b4b241aa">  | <video src="https://github.com/user-attachments/assets/c6d17b7b-7c9a-47c3-8286-2d9b5720f261"> |
```jsx
import React, {useEffect} from 'react';
import {Animated, useAnimatedValue, View} from 'react-native';
import {Rect, Svg} from 'react-native-svg';
const AnimatedRect = …
```

fix: animated transform last frame

---

apple/Filters/RNSVGFeComposite.mm
src/elements/filters/FeComposite.tsx

Fixes #2552 by adding default value for k1, k2, k3, k4 according to the spec: https://www.w3.org/TR/SVG11/filters.html#feCompositeElement
> If the attribute is not specified, the effect is as if a value of 0 were specified.
[Repro from issue 2552](https://github.com/TomCorvus/RNSVG/blob/main/App.js)

fix: FeComposite add default value for k1...4

---

src/xml.tsx

When using `SvgXml` or `SvgCss`, an `id` attribute gets converted into a `number` instead of a `string`, which causes a crash because the native side expects a string value.
```js
import {SvgXml} from 'react-native-svg';
import {SvgCss} from 'react-native-svg/css';
```
This example should not crash:
```jsx
import {SvgCss} from 'react-native-svg/css';
const svgXml = `
<svg width="100" height="100" viewBox="0 0 100 100">
<filter x="0%" y="0%" width="100" height="100" id="0123456789">
<feFlood flood-color="red" />
</filter>
<circle cx="50" cy="50" r="50" filter="url(#0123456789)" />
</svg>
`;
function Example() {
return <SvgCss xml={svgXml} />;
}
```

fix: do not parse id as number in any case

---

apple/RNSVGRenderable.mm

This is a blind fix for issue #2566 that resets the caller on `prepareForRecycle`. While it should help address the overflow happening in some cases, I cannot guarantee that it will fully resolve the issue due to the lack of a reproducible scenario.

fix: currentColor overflow

---

package.json

Add a newly introduced field `ios.componentProvider` to the `codegen` configuration to create an association map between JS components and their native implementations. 
When this field is defined, it is used and codegen don't crawl the file system looking for the mapping. You can find the documentation for it here: https://github.com/facebook/react-native-website/pull/4388/files#diff-7fbb6ff2e58f8bd50d2763e551c63e1816adb6d593f40d489785b575b0e82718R76
Running `pod install` in the `tests-example` will currently hang and eventually crash, as it attempts to crawl through the entire repository.

feat: add codegen `ios.componentProvider`

---

RNSVG.podspec

Fixes #2571.
Since filter shaders are already provided as compiled `*.metallib` files, there is no need to include `*.metal` files in the `source_files` list.

remove: *.metal from podspec source_files

---

apple/RNSVGRenderable.mm

This is another fix for issue https://github.com/software-mansion/react-native-svg/issues/2566 that also resets the color on prepareForRecycle (in the same manner of this fix https://github.com/software-mansion/react-native-svg/pull/2570). I also don't have a sandboxed reproduce, but was able to verify the fix on my company's code which I unfortunately can't share.
OS | Implemented
-- | --
iOS | ✅
MacOS | ✅

fix: currentColor stale value

---

.github/workflows/e2e-ios.yml
apps/common/example/e2e/TestingView.tsx
apps/common/example/e2e/index.tsx
apps/common/example/index.tsx

Fix broken E2E iOS tests
CI should be green

test: fix e2e tests

---

src/lib/util.ts

The SVG specification does not strictly standardize linking, and most browsers permit the use of `'` as a wrapper in `url` links. As a result, I've added support for URLs such as `url('#id')`. 
`url(#id)` and `url('#id')` should do the exact same thing.
Closes #1768

feat: allow single quote ID wrapper

---

android/build.gradle
android/src/main/AndroidManifest.xml

Fixes #2599 
Starting with `v15.8.0`, we support `react-native@0.73+`, which eliminates the need to worry about AGP versions below 7. Consequently, the `package` attribute in `AndroidManifest.xml` can be safely removed, along with the corresponding check in `build.gradle`.
Build the app on all supported versions

fix: remove package from AndroidManifest.xml

---

android/build.gradle
android/src/main/jni/CMakeLists.txt

Fix typo in CMakeLists.txt flags and use `ReactAndroid_VERSION_MINOR` instead of `REACT_NATIVE_MINOR_VERSION`
Example apps should build without warnings/errors on 0.73+ as well as on 0.77.0-rc.6

fix: CMake flags

---

package.json

Hotfix for #2606, where `RNSVG.podspec` imports `scripts/rnsvg_utils.rb` but `scripts` catalog is not included in the release.
Closes #2606
```bash
❯ bundle exec pod install
[!] Invalid `Podfile` file:
[!] Invalid `RNSVG.podspec` file: cannot load such file -- /node_modules/react-native-svg/scripts/rnsvg_utils.
>  require_relative './scripts/rnsvg_utils'
#
```

fix: include `scripts/rnsvg_utils.rb` in release

---

android/src/main/java/com/horcrux/svg/VirtualView.java
apple/Elements/RNSVGSvgView.mm

Fixes #2585 
Improve the `onPress` events by ignoring touches outside the `Svg` view. This is implemented as follows:
* on Android by clipping the Android's 	element dimensions to (0, 0, canvas width, canvas height)
* on Apple by improving `hitTest` to exclude touches outside the bounds of (0, 0, bounds width, bounds height)
https://github.com/user-attachments/assets/59417493-d849-47df-84e8-d5b0a6045b00

fix: properly handle touch events outside the Svg

---

common/cpp/react/renderer/components/rnsvg/RNSVGLayoutableShadowNode.cpp

Fixes #2610
It's more of a hack than the best fix for that; however, it's a regression that we should address.
Test case provided in #2610

fix: don't set zero dimensions on RNSVGGroup

---

src/elements/filters/FeBlend.tsx
src/elements/filters/FeColorMatrix.tsx
src/elements/filters/FeComponentTransfer.tsx
src/elements/filters/FeComponentTransferFunction.tsx
src/elements/filters/FeComposite.tsx
src/elements/filters/FeDropShadow.tsx
src/elements/filters/FeFlood.tsx
src/elements/filters/FeGaussianBlur.tsx
src/elements/filters/FeMerge.tsx
src/elements/filters/FeMergeNode.tsx
src/elements/filters/FeOffset.tsx
src/elements/filters/Filter.tsx

* Add results alias in `FeDropShadow`
* Import React in every tsx filter file to satisfy typescript/eslint
* Replace `<>` with `<React.Fragment>` in `FeDropShadow`

fix: FeDropShadow results and import react

---

src/web/WebShape.ts
src/xml.tsx

Fixed the types when building with React Native 0.78+ and React 19+ as mentioned [here](https://react.dev/blog/2024/04/25/react-19-upgrade-guide#the-jsx-namespace-in-typescript). None of the changes should impact production code since this is just updating types.
Run `yarn bob` using React 18 and React 19. It should compile without any type errors (CI/CD should also cover this).
Install react-native-svg in a project running React Native 0.78 and React 19 and set `skipLibCheck` to `false` (or simply upgrade React types to 19 in the example apps).
Compile the typescript code.
| Web     |    ✅      |

fix: types to support react 19

---

android/src/main/java/com/horcrux/svg/RenderableView.java

When animating a strokeDasharray, JS parsing is bypassed, which results in an incorrect array length when only one element is animated. This fix prevents Android's illegal state with odd array length.
This component should not crash:
```tsx
import React from 'react';
import {Button} from 'react-native';
import Animated, {
Easing,
useAnimatedProps,
useSharedValue,
withTiming,
} from 'react-native-reanimated';
import {Path, Svg} from 'react-native-svg';
const AnimatedPath = Animated.createAnimatedComponent(Path);
const AnimatedImplementation = ({isFocused = false}: {isFocused: boolean}) => {
const progress = useSharedValue(isFocused ? 30 : 0);
React.useEffect(() => {
progress.value = withTiming(isFocused ? 30 : 0, {
duration: isFocused ? 400 : 300,
easing: Easing.inOut(Easing.ease),
});
}, …
```

fix: animating single strokeDasharray on Android

---

common/cpp/react/renderer/components/rnsvg/RNSVGConcreteShadowNode.h

This wasn't present in older versions of React Native, and is removed from newer versions. It was kind of meant to be hidden, with the default value used, but was fully public. Let's rely on the default `false` instead of specifying an explicit value, for compatibility of versions of RN without it.
GitHub Actions building the project

Remove explicit value for `usesMapBufferForStateData` template parameter

---

android/src/main/jni/CMakeLists.txt

Silencing warnings generated by generated codegen code. Analogous PR to https://github.com/software-mansion/react-native-screens/pull/2707
Fixes
🚀

chore: silence irrelevant codegen warnings

---

android/src/main/jni/CMakeLists.txt

chore: format CMakeLists.txt

---

apps/paper-macos-example/macos/Podfile

Turning off Hermes in the Podfile tends to crash the installation pods
Analogous changes in [react-native-reanimated](https://github.com/software-mansion/react-native-reanimated/blob/main/apps/macos-example/macos/Podfile#L16)
``cd apps/paper-macos-example/macos/ && bundle exec pod install && bundle exec pod install``

chore: turn off Hermes in paper-macos-example

---

.github/workflows/e2e-ios.yml
.github/workflows/ios-build-test.yml
.github/workflows/macos-build-test.yml

This PR improve `Example iOS check`, `E2E iOS` and `Example macOS check` CI workflows by adding to them extra steps: 
- remove pods if `Install Pods` step failed
- reinstall pods if `Remove pods` step was successful
Run `Example iOS check`, `E2E iOS` and `Example macOS check` CI workflows.
| Android |    ❌      |
| Web     |    ❌      |

feat: add handling pod install failure in apple CI

---

src/elements/Svg.tsx

This PR fixes issue: #2689 
In the SVG component when we do not pass `width` and `height` props, we set them to 100%. This caused problems when position is set to absolute because the SVG would expand beyond its parent. I added an extra check to only set width/height to 100% if `position !== 'absolute'`.
Run the example from issue: #2689 and check if Views are filled properly
| Web     |    ✅      |

fix: prevent parent expansion by skipping width/height setting to 100% on absolute SVG

---

android/src/main/java/com/horcrux/svg/MarkerView.java

This PR fixes: #1410 
Remove dividing by `mScale` when calculating marker width and height.
Run example from issue: #1410, and check if markers are displayed properly.

fix: scalling width and height in marker on Android

---

apple/RNSVGNode.mm

Remove setting variables inside `RNSVGNode` with `self.` and use underscore `_` instead.
- Example app -> TouchEvents
- Create `G` with some `Rect` inside it and set opacity for `G` to `0` (Content inside `G` should be invisible)
| MacOS   |    ❌      |
| Android |    ❌      |
| Web     |    ❌      |

fix: remove setting opacity with self keyword inside RNSVGNode
