software-mansion/react-native-svg

- lib/fillFilter.js
Fix for condition where both fill and fillOpacity properties are
undefined
> FIX: Check for fillOpacity when fill is undefined

- elements/ViewBox.js
This duplicate line introduces bugs in certain configurations ("attempting to redefine preserveAspectRatio").
> Remove unnecessary duplicate preserveAspectRatio

- elements/Circle.js
- elements/ClipPath.js
- elements/Defs.js
- elements/Ellipse.js
- elements/G.js
- elements/Gradient.js
- elements/Image.js
- elements/Line.js
- elements/LinearGradient.js
- elements/Path.js
- elements/Pattern.js
- elements/Polygon.js
- elements/Polyline.js
- elements/RadialGradient.js
- elements/Rect.js
- elements/Shape.js
- elements/Stop.js
- elements/Svg.js
- elements/Symbol.js
- elements/Text.js
- elements/Use.js
- elements/ViewBox.js
- lib/numberProp.js
- lib/props.js
- package.json
#35 with the pull request, should be able to upgrade react-native to version 0.25.0. Tested on both iOS and Android.
> React API must be now required from react package

- ios/Elements/RNSVGSvgView.m
- ios/RNSVGNode.h
- ios/RNSVGNode.m
Just applied that fix from RN: https://github.com/facebook/react-native/commit/b0fed416cbb510009bef1ae721e564d04d053cc5
> Fixes #62: Use ReactNative rendering methods

- android/src/main/java/com/horcrux/svg/RNSVGSvgView.java
add new params to TouchEvent.obtain method to fix #70
> fix #70 android compile failed on rn 0.29.0

- android/build.gradle
Upgrade gradle to match the version in react native.
Change url of react native repository so that it loads the correct local version.
> Upgrade gradle version and react native local url

- lib/extract/extractText.js
Currently, if you pass `number` to `Text` your app will be broken.
> fix passing numbers to Text element

- android/src/main/java/com/horcrux/svg/RNSVGTextShadowNode.java
after text is changed on android it's not updated #115
> Fix android text update #115

- elements/Circle.js
- elements/ClipPath.js
- elements/Defs.js
- elements/Ellipse.js
- elements/G.js
- elements/Image.js
- elements/Line.js
- elements/LinearGradient.js
- elements/Path.js
- elements/RadialGradient.js
- elements/Rect.js
- elements/Text.js
- elements/Use.js
- elements/ViewBox.js
- package.json
This changes has been tested in our app and we didn't find any issue. The changes are a simple find and replace with the new path for the import and should be ok to be merged now. 
Thanks for all your effort in your awesome library.
> Fixes #188 in the master repo by replacing the path in the import with the new path

- ios/Utils/RNSVGPathParser.m
- package.json
> Fix curveTo bug

- android/src/main/java/com/horcrux/svg/ImageShadowNode.java
- elements/Image.js
- ios/Elements/RNSVGImage.m
Have not tested for iPhone yet. Opening PR for discussions.
> Data URI support for href in react-native-svg Image tag

- ios/RNSVG.xcodeproj/project.pbxproj
> Add tvOS target

- README.md
The given link didn't exist any more.
> Docs: update TouchEvents examples

- elements/Svg.js
According to react native 0.44 changes. 
(#338 #331)
> Migrate from View.propTypes to ViewPropTypes

- elements/ClipPath.js
- elements/Image.js
- elements/LinearGradient.js
- elements/Path.js
- elements/Pattern.js
- elements/Polygon.js
- elements/Polyline.js
- elements/RadialGradient.js
- elements/Stop.js
- elements/Svg.js
- elements/Symbol.js
- elements/TSpan.js
- elements/Text.js
- elements/TextPath.js
- elements/Use.js
- lib/extract/extractViewBox.js
- lib/props.js
- package.json
> Replaced React and RN PropTypes with prop-types package

- android/src/main/java/com/horcrux/svg/SvgPackage.java
fixed react-native@0.47.0-rc.1 compatibility issue 
#397
> fixed issue #397

- elements/Circle.js
- elements/ClipPath.js
- elements/Defs.js
- elements/Ellipse.js
- elements/G.js
- elements/Image.js
- elements/Line.js
- elements/LinearGradient.js
- elements/Path.js
- elements/RadialGradient.js
- elements/Rect.js
- elements/Symbol.js
- elements/TSpan.js
- elements/Text.js
- elements/TextPath.js
- elements/Use.js
- lib/extract/extractViewBox.js
fixed rn-0.46 compatibility issue
https://github.com/react-native-community/react-native-svg/issues/360
> fixed issue #360

- lib/extract/extractProps.js
- lib/extract/extractTransform.js
- package.json
Support for transform lists with repeated occurrences of one type of transform.
Support for optional arguments.
https://www.w3.org/TR/SVG/coords.html#TransformAttribute
https://developer.mozilla.org/en-US/docs/Web/SVG/Attribute/transform
> Implement correct transform parser

- index.d.ts
> added missing class and offset

- ios/RNSVG.xcodeproj/project.pbxproj
@msand please have a look and merge this when you get a chance :)
> Fix tvOS compile issue (BezierElement.m)

- android/src/main/java/com/horcrux/svg/ImageShadowNode.java
- ios/Elements/RNSVGImage.h
- ios/Elements/RNSVGImage.m
- ios/ViewManagers/RNSVGImageManager.m
> 5.5.1 Load Image from URL

- ios/Elements/RNSVGImage.m
Ref #630 
Quick patch to fix after 6.3.0 merge.
> 6.3.0 [iOS] Fix Load Image from URL

- ios/RNSVG.xcodeproj/project.pbxproj
Added missing files to TVOS target.
> Fixed TVOS target

- android/src/main/java/com/horcrux/svg/Brush.java
Handles erroneous gradient which contains only one stop or two
stops at the same place, but merged into one stop by extractGradient().
> [android] Handle gracefully gradients with only one stop

- android/src/main/java/com/horcrux/svg/RenderableShadowNode.java
- android/src/main/java/com/horcrux/svg/TSpanShadowNode.java
Sometimes a NullPointerException occurs when using the computeBounds function, this fixes these by simply adding additional null pointer checks to 2 specific places.
I posted about this as an issue, but thought it'd be faster to create a Pull Request.
Best Regards
> Fixed NullPointerException

- android/src/main/java/com/horcrux/svg/SvgView.java
fix bug com.horcrux.svg.SvgView#getShadowNode return null
add null pointer check
fixed #695
> [android]fix NullPointerException

- android/src/main/java/com/horcrux/svg/SvgView.java
- android/src/main/java/com/horcrux/svg/SvgViewManager.java
Fixes issue https://github.com/react-native-community/react-native-svg/issues/784
> Let SvgViewManager handle removing node and view references.

- android/build.gradle
upgrading gradle to 3.2.1 also seems to solve issue #868
> upgraded gradle to 3.2.1

- android/src/main/java/com/horcrux/svg/SvgView.java
> Prevents early rendering.

- README.md
* plus minor formatting proposals
> Added closing ` on paragraph #120

- README.md
It took time for me to understand parameters for path.
Could you add a link to a page that explains about parameters for path commands?
Thank you for sharing useful project.
> Add link of w3.org to reference params for path

- lib/extract/extractGradient.js
This change makes the 'offset' prop optional in Gradients, using '0' as a default if offset is not supplied.
Some design tools (e.g. Figma) export SVGs in such a format that the first <Stop.. /> element in a LinearGradient does not supply an offset prop. As a result, the warning is thrown when the SVG is used. The SVG seems to render correctly when an offset of 0 is supplied in these case. Since it would be difficult to change Figma's SVG export code (and there may be other services that export in a similar fashion) this seemed like a reasonable way to fix it.
Use SVG in app in simulator, warning appears. After the change, the SVG renders exactly the same and no warning is displayed.
An SVG that uses a Gradient with Stop elements.
Place SVG in simple app and run in iOS/Android simulator - …
> make offset optional in gradient

- README.md
> Update README.md, add progaurd troubleshooting section

- android/src/main/java/com/horcrux/svg/PathParser.java
Quick fix for a missing semicolon in android/src/main/java/com/horcrux/svg/PathParser.java after update to v9.8.2
> Fix compilation because of missing semicolon

- README.md
> docs: update with Expo installation steps

- README.md
* Added example of using `<SvgCss>` and `<SvgCssUri>` components
* Small cleaning of extra whitespace
> Readme update: Support for CSS

- android/src/main/java/com/horcrux/svg/TSpanView.java
Should still add https://www.w3.org/TR/SVG2/text.html#DirectionProperty and make the default text direction depend on that.
> feat(android): Bidi

- src/index.d.ts
This PR adding missing Marker related type definition. fixes #1208 
> added Marker component to definition file

- CHANGELOG.md
- CODE_OF_CONDUCT.md
- CONTRIBUTING.md
- package-lock.json
- package.json
- src/index.d.ts
This is a continuation of [this PR](https://github.com/react-native-community/react-native-svg/pull/1209)
> added common Marker props to CommonPathProps

- android/.npmignore
This is the continuation of [this PR](https://github.com/react-native-community/react-native-svg/pull/1190)
by this change, the android folder will look like below
> ignore some more file and folders in android path

- android/src/main/java/com/horcrux/svg/ForeignObjectView.java
- android/src/main/java/com/horcrux/svg/RenderableViewManager.java
- android/src/main/java/com/horcrux/svg/SvgPackage.java
- ios/Elements/RNSVGForeignObject.h
- ios/Elements/RNSVGForeignObject.m
- ios/Elements/RNSVGGroup.h
- ios/Elements/RNSVGGroup.m
- ios/ViewManagers/RNSVGForeignObjectManager.h
- ios/ViewManagers/RNSVGForeignObjectManager.m
- src/ReactNativeSVG.ts
- src/ReactNativeSVG.web.ts
- src/elements/ForeignObject.tsx
- src/elements/G.tsx
- src/index.d.ts
- src/index.js.flow
This PR adds `ForeignObject` support to this library and resolve #447 
It can be used like this:
```js
<View style={{flex: 1, justifyContent: 'center'}}>
<Svg height="50%">
<Defs>
<LinearGradient
id="Gradient"
gradientUnits="userSpaceOnUse"
x1="0"
y1="0"
x2="800"
y2="0">
<Stop offset="0" stopColor="white" stopOpacity="0.2" />
<Stop offset="1" stopColor="white" stopOpacity="1" />
</LinearGradient>
<Mask
id="Mask"
maskUnits="userSpaceOnUse"
x="0"
y="0"
width="800"
height="300">
<Rect x="0" y="0" width="800" height="300" fill="url(#Gradient)" />
</Mask>
</Defs>
<G mask="url(#Mask)">
<Circle cx={50} cy={70} r={65} />
<ForeignObject x={50} y={50}>
<View style={{width: 200, height: 400, flex: 1}}>
<Image
style={{width: 200, height: 200}}
source={{
uri: 'https://picsum.photos/200/200',
}}
/> …
```
> Added support for ForeignObject

- src/index.d.ts
This prop is used when creating an `<Image>` in a `<Defs>` element.
| iOS     |         |
| Android |        |
> fix: Add missing id param to ImageProps

- .github/ISSUE_TEMPLATE.md
- .github/ISSUE_TEMPLATE/bug_report.md
- .github/ISSUE_TEMPLATE/feature_request.md
- .github/ISSUE_TEMPLATE/question.md
- .github/PULL_REQUEST_TEMPLATE.md
- .github/stale.yml
- android/build.gradle
- moved safeExtGet to out of `buildscript` block, because it's no longer needed to be there (previously we needed it there for getting AGP version from root project)
- bumped AGP version to 3.5.3
- replace `${safeExtGet('reactnativeVersion', '+')}` with `+`, because react-native version automatically resolved by npm and it does not need to handled using `safeExtGet`
> chore: Refactored Gradle setup

- android/src/main/java/com/horcrux/svg/PathParser.java
The current error logging is not very helpful for debugging issues like https://github.com/react-native-community/react-native-svg/issues/1282
This doesn't directly solve any issue but to make debugging easier
See PR
`PathParser`
Built and ran example app.
N/A
N/A
> refactor: improve error logging in PathParser

- src/index.js.flow
- src/xml.tsx
This solves #1105 and only affects the ts part.
> feat(svgUri): add onError prop to SvgUri/Xml/Ast

- package-lock.json
- package.json
- src/css.tsx
nth-check has a security vulnerability and is depended on by css-select. Updates css-select to fix.
> Update to css-select to avoid security warnings

- package.json
- src/index.js.flow
- yarn.lock
Changed `semantic-release` to `release-it`.
> feat: add release-it

- .npmignore
- package.json
> Do not include build artifacts in the npm package

- CONTRIBUTING.md
Fixed some vocabulary issues in Contributing file.
> Fixed some vocabulary issues in Contributing file

- TestsExample/App.js
- TestsExample/assets/ruby.svg
- TestsExample/ios/Podfile.lock
- TestsExample/src/Test1813.tsx
- TestsExample/yarn.lock
- src/LocalSvg.tsx
- src/ReactNativeSVG.ts
- src/css.tsx
- src/xml.tsx
PR correctly exporting rest of the props and adding `onError` to parsing in other `Svg` components.
`Test1813.tsx` in `TestsExample` project.
> fix: correctly export rest of the props and add onError to parsing

- .github/workflows/ios-build-test.yml
PR based on https://github.com/software-mansion/react-native-reanimated/pull/3448 which should improve the caches of `iOS` CI jobs resulting in smaller build time.
> feat: improve ios ci job

- .git-blame-ignore-revs
Added formatting PR to ignored blame to help navigating through commits.
> chore: remove formatting from blame

- README.md
> chore: add react-native-svg banner to README

- src/elements/Image.tsx
> fix: make image props extend CommonPathProps

- common/cpp/react/renderer/components/rnsvg/RNSVGImageShadowNode.h
This PR solves #2077.
I'm too bad at C++ to know whether this is idiomatic code, however.
> Fix syntax error in RNSVGImageShadowNode::initialStateData

- USAGE.md
- src/xml.tsx
PR adding changes from linting and prettiering main.
> chore: run prettier and lint

- .eslintignore
- .github/workflows/macos-build-test.yml
- Example/ios/Podfile.lock
- Example/macos/.gitignore
- Example/macos/.xcode.env
- Example/macos/Example-macOS/AppDelegate.h
- Example/macos/Example-macOS/AppDelegate.mm
- Example/macos/Example-macOS/Assets.xcassets/AppIcon.appiconset/Contents.json
- Example/macos/Example-macOS/Assets.xcassets/Contents.json
- Example/macos/Example-macOS/Base.lproj/Main.storyboard
- Example/macos/Example-macOS/Example.entitlements
- Example/macos/Example-macOS/Info.plist
- Example/macos/Example-macOS/main.m
- Example/macos/Example.xcodeproj/project.pbxproj
- Example/macos/Example.xcodeproj/xcshareddata/xcschemes/Example-macOS.xcscheme
- Example/macos/Example.xcworkspace/contents.xcworkspacedata
- Example/macos/Example.xcworkspace/xcshareddata/IDEWorkspaceChecks.plist
- Example/macos/Podfile
- Example/macos/Podfile.lock
- Example/metro.config.js
- Example/package.json
- Example/src/App.tsx
- Example/yarn.lock
- apple/Elements/RNSVGSvgView.mm
- apple/RNSVGRenderable.mm
PR restoring `macos` CI job and restoring usage of `UIGraphicsBeginImageContextWithOptions` on `macos` since there is no implementation for `UIGraphicsImageRendererFormat` there yet.
Run `yarn macos` in `Example` folder and see that all works correctly.
> feat: add macos back to Example app

- android/src/main/jni/CMakeLists.txt
> Fix CMakeLists for Android

- windows/RNSVG/RNSVG.vcxproj
On Windows, it's no longer possible to build the release because some lib are missing
https://github.com/software-mansion/react-native-svg/issues/2185
https://github.com/software-mansion/react-native-svg/issues/2216
[set up a classical RNW project.](https://github.com/software-mansion/react-native-svg/issues/2185#issue-2016672833)
run 
```
npx react-native run-windows --release
```
now the build is working :_) 
| Windows|    ✅     |
> Add dxguid.lib to release action

- TestsExample/App.js
- TestsExample/src/Test2148.tsx
- src/xml.tsx
We want to add the ability to handle the Error when someone passes the wrong URI to the `SvgFromUri` component.
Closes #2148 
Manual tests in TestsExample app. (Test2148)
> Handle error when pass wrong uri to SvgFromUri component

- README.md
This PR adds a "Hire us" section to the README with a link to the contact form.
> chore: add hire us section to readme

- .github/workflows/close-when-stale.yml
Add GH action to close issues that were without response to the question.
Check if that GH action closes the issue if no one response to the question.
> feat: github action close-when-stale

- .github/ISSUE_TEMPLATE/bug_report.yaml
> fix: issue template

- Example/package.json
- Example/yarn.lock
Fix problem package.json
install packages and run apps.
| Web     |    ✅    |
> fix: example app package.json file and yarn.lock

- .github/workflows/needs-more-info.yml
update check of react-native-svg version in GitHub workflow.
> feat: update needs-more-info git workflow

- TestsExample/src/Test1442.tsx
- android/src/main/java/com/horcrux/svg/events/SvgLoadEvent.java
- apple/Elements/RNSVGImage.mm
- src/elements/Image.tsx
- src/fabric/ImageNativeComponent.ts
Change data structure returned from the Image onLoad event.
Add fix in new arch for returned sizes.
Manually test in both architectures and platforms.
| iOS     |      ✅     |
> Fix: image onLoad props

- package.json
Fixes following error while commiting:
```
✖ yarn format-js:
[error] No files matching the pattern were found: "./Example/src/**/*.tsx".
error Command failed with exit code 2.
```
Run `yarn format-js` or do a commit so hook will get ran.
-
See test plan
- [] I updated the typed files (typescript)
> fix: fix format-js task to reflect changes made to folder structure

- apple/Filters/RNSVGFilter.mm
- apple/RNSVGRenderable.mm
- apple/Utils/RNSVGRenderUtils.h
- apple/Utils/RNSVGRenderUtils.mm
Fixed rendering issues on macOS and iOS after merging Mask and Filter changes together.
Example app
> fix: mask and filters rendering issues

- .github/workflows/windows-build-test.yml
Improves the windows build time. 
Before:
After:
| Windows |    ✅     |
> feat: improve windows ci job

- android/src/main/java/com/horcrux/svg/ImageView.java
- android/src/main/java/com/horcrux/svg/RenderableView.java
- android/src/main/java/com/horcrux/svg/events/SvgLoadEvent.java
- apps/test-examples/App.js
- common/cpp/react/renderer/components/rnsvg/RNSVGImageState.h
- macos-example/__tests__/App.test.tsx
- tests-example/__tests__/App.test.tsx
> feat: format project and change in test example default component

- android/src/main/java/com/horcrux/svg/RenderableViewManager.java
- src/elements/filters/FeOffset.tsx
- src/lib/extract/extractFilter.ts
This PR contains two small refactors of filters:
* extract common props on ViewManagers on Android
* remove unnecessary extract in `FeOffset` filter
> refactor: small changes to filters

- src/ReactNativeSVG.web.ts
- src/lib/extract/extractTransform.ts
Fix type problem in `ReactNativeSvg.web.ts`
> fix: type problem ReactNativeSvg.web.ts

- apple/Filters/RNSVGFeMerge.mm
- apple/Filters/RNSVGFeOffset.mm
- fabric-macos-example/patches/react-native-reanimated+3.9.0.patch
Fix some crashes on MacOS
* patch `reanimated`
* update fabric type
* invert axis in `FeOffset`
> fix: mac os crashes

- src/web/utils/prepare.ts
Change way changing onPress prop in the web platform
> fix: change way passing onPress prop

- apple/Filters/RNSVGFeGaussianBlur.mm
- apps/examples/src/examples/Filters/FeGaussianBlur.tsx
Scale stdDeviation by screenScale (density) on Apple devices in order to achive the same results as on web
> fix: FeGaussianBlur stdDeviation on Apple

- android/src/main/java/com/horcrux/svg/SvgView.java
- android/src/transformRn73/java/com/horcrux/svg/SvgViewManager.java
Undo these changes https://github.com/software-mansion/react-native-svg/pull/2403/files#diff-7f8adeb6e7faded1a7ef711b4fa9d2b12d29ff386217e838c4551866afdd8bef that introduced a bug described here https://github.com/software-mansion/react-native-svg/issues/2442#issuecomment-2354170651
> fix: transform scale on android

- USAGE.md
- android/src/main/java/com/horcrux/svg/RenderableView.java
- android/src/transformRn73/java/com/horcrux/svg/SvgViewManager.java
Formatting and rename variable committed in #2415
> style: format and rename variables

- apple/RNSVGRenderable.h
- apple/RNSVGRenderable.mm
- apple/Utils/RNSVGFabricConversions.h
Invalidate element when `color` prop changes.
> feat: invalidate on color change

- babel.config.js
- package.json
- yarn.lock
Change babel preset from `metro-react-native-babel-preset` to `@react-native/babel-preset` to properly parse flow files.
> chore: change babel preset to `@react-native/babel-preset`

- example/ios/Podfile.lock
- fabric-example/ios/Podfile.lock
- fabric-macos-example/macos/Podfile.lock
- paper-macos-example/macos/Podfile.lock
- tests-example/ios/Podfile.lock
Regenerate Podfile.lock in example apps using proper cocoapods version
> chore: regenerate Podfile.lock in example apps

- tests-example/ios/Podfile.lock
- tests-example/package.json
- tests-example/yarn.lock
bump TestsExample app to react-native@0.76.0-rc.4
> chore: bump TestsExample app to react-native@0.76.0-rc.4

- tests-example/android/gradle/wrapper/gradle-wrapper.properties
- tests-example/ios/Podfile.lock
- tests-example/package.json
- tests-example/yarn.lock
Bump tests-example app to `react-native@0.76.0-rc.5`
> chore: bump example app to react-native@0.76.0-rc.5

- apps/examples/src/e2e/icon.tsx
Give E2E own icon instead of copy of circle
> docs: give E2E own icon

- apps/common/tsconfig.json
Fixes small mistake introduced in #2507
> fix: example types

- android/src/main/java/com/horcrux/svg/FeBlendView.java
Use old-style switch statement.
Closes #2537
> refactor: use old style switch statement

- android/src/main/java/com/horcrux/svg/FeCompositeView.java
Use old-style switch statement in `FeCompositeView.java`.
> refactor: use old style switch statement in FeCompositeView.java

- apps/tests-example/Gemfile
- apps/tests-example/Gemfile.lock
- apps/tests-example/ios/Podfile.lock
- apps/tests-example/package.json
- apps/tests-example/yarn.lock
Upgrade `tests-example` to `react-native@0.77.0-rc.7`
> chore: upgrade react-native to 0.77.0-rc.7

- USAGE.md
`USAGE.md` had some incorrect import paths. This minor PR fixes those.
Test that the updated import paths are functional, and are consistent with the rest of `USAGE.md`.
N/A
N/A
N/A
- I have tested this on a device and a simulator
- I added documentation in `README.md`
- I updated the typed files (typescript)
- I added a test for the API in the `__tests__` folder
> docs: fix incorrect imports
